// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	sync "sync"

	snapshota "istio.io/istio/pkg/mcp/snapshot"
)

type Setter struct {
	SetSnapshotStub        func(string, snapshota.Snapshot)
	setSnapshotMutex       sync.RWMutex
	setSnapshotArgsForCall []struct {
		arg1 string
		arg2 snapshota.Snapshot
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Setter) SetSnapshot(arg1 string, arg2 snapshota.Snapshot) {
	fake.setSnapshotMutex.Lock()
	fake.setSnapshotArgsForCall = append(fake.setSnapshotArgsForCall, struct {
		arg1 string
		arg2 snapshota.Snapshot
	}{arg1, arg2})
	fake.recordInvocation("SetSnapshot", []interface{}{arg1, arg2})
	fake.setSnapshotMutex.Unlock()
	if fake.SetSnapshotStub != nil {
		fake.SetSnapshotStub(arg1, arg2)
	}
}

func (fake *Setter) SetSnapshotCallCount() int {
	fake.setSnapshotMutex.RLock()
	defer fake.setSnapshotMutex.RUnlock()
	return len(fake.setSnapshotArgsForCall)
}

func (fake *Setter) SetSnapshotCalls(stub func(string, snapshota.Snapshot)) {
	fake.setSnapshotMutex.Lock()
	defer fake.setSnapshotMutex.Unlock()
	fake.SetSnapshotStub = stub
}

func (fake *Setter) SetSnapshotArgsForCall(i int) (string, snapshota.Snapshot) {
	fake.setSnapshotMutex.RLock()
	defer fake.setSnapshotMutex.RUnlock()
	argsForCall := fake.setSnapshotArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Setter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.setSnapshotMutex.RLock()
	defer fake.setSnapshotMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Setter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
