// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/copilot/models"
)

type RoutesRepo struct {
	GetStub        func(guid models.RouteGUID) (*models.Route, bool)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		guid models.RouteGUID
	}
	getReturns struct {
		result1 *models.Route
		result2 bool
	}
	getReturnsOnCall map[int]struct {
		result1 *models.Route
		result2 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RoutesRepo) Get(guid models.RouteGUID) (*models.Route, bool) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		guid models.RouteGUID
	}{guid})
	fake.recordInvocation("Get", []interface{}{guid})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(guid)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getReturns.result1, fake.getReturns.result2
}

func (fake *RoutesRepo) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *RoutesRepo) GetArgsForCall(i int) models.RouteGUID {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].guid
}

func (fake *RoutesRepo) GetReturns(result1 *models.Route, result2 bool) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *models.Route
		result2 bool
	}{result1, result2}
}

func (fake *RoutesRepo) GetReturnsOnCall(i int, result1 *models.Route, result2 bool) {
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *models.Route
			result2 bool
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *models.Route
		result2 bool
	}{result1, result2}
}

func (fake *RoutesRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RoutesRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
