// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type VIPProvider struct {
	GetStub        func(hostname string) string
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		hostname string
	}
	getReturns struct {
		result1 string
	}
	getReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *VIPProvider) Get(hostname string) string {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		hostname string
	}{hostname})
	fake.recordInvocation("Get", []interface{}{hostname})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(hostname)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.getReturns.result1
}

func (fake *VIPProvider) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *VIPProvider) GetArgsForCall(i int) string {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].hostname
}

func (fake *VIPProvider) GetReturns(result1 string) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 string
	}{result1}
}

func (fake *VIPProvider) GetReturnsOnCall(i int, result1 string) {
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *VIPProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *VIPProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
