# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud_controller.proto

require 'google/protobuf'

require 'common_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "api.ListCfRoutesRequest" do
  end
  add_message "api.ListCfRoutesResponse" do
    map :routes, :string, :message, 1, "api.Route"
  end
  add_message "api.ListCapiDiegoProcessAssociationsRequest" do
  end
  add_message "api.DiegoProcessGuids" do
    repeated :diego_process_guids, :string, 1
  end
  add_message "api.ListCapiDiegoProcessAssociationsResponse" do
    map :capi_diego_process_associations, :string, :message, 1, "api.DiegoProcessGuids"
  end
  add_message "api.Route" do
    optional :guid, :string, 1
    optional :host, :string, 2
    optional :path, :string, 3
    repeated :destinations, :message, 4, "api.Destination"
  end
  add_message "api.UpsertRouteRequest" do
    optional :route, :message, 1, "api.Route"
  end
  add_message "api.UpsertRouteResponse" do
  end
  add_message "api.DeleteRouteRequest" do
    optional :guid, :string, 1
  end
  add_message "api.DeleteRouteResponse" do
  end
  add_message "api.Destination" do
    optional :capi_process_guid, :string, 1
    optional :weight, :uint32, 2
    optional :port, :uint32, 3
  end
  add_message "api.CapiDiegoProcessAssociation" do
    optional :capi_process_guid, :string, 1
    repeated :diego_process_guids, :string, 2
  end
  add_message "api.UpsertCapiDiegoProcessAssociationRequest" do
    optional :capi_diego_process_association, :message, 1, "api.CapiDiegoProcessAssociation"
  end
  add_message "api.UpsertCapiDiegoProcessAssociationResponse" do
  end
  add_message "api.DeleteCapiDiegoProcessAssociationRequest" do
    optional :capi_process_guid, :string, 1
  end
  add_message "api.DeleteCapiDiegoProcessAssociationResponse" do
  end
  add_message "api.BulkSyncRequest" do
    repeated :routes, :message, 2, "api.Route"
    repeated :capi_diego_process_associations, :message, 3, "api.CapiDiegoProcessAssociation"
  end
  add_message "api.BulkSyncResponse" do
  end
end

module Api
  ListCfRoutesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.ListCfRoutesRequest").msgclass
  ListCfRoutesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.ListCfRoutesResponse").msgclass
  ListCapiDiegoProcessAssociationsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.ListCapiDiegoProcessAssociationsRequest").msgclass
  DiegoProcessGuids = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.DiegoProcessGuids").msgclass
  ListCapiDiegoProcessAssociationsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.ListCapiDiegoProcessAssociationsResponse").msgclass
  Route = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Route").msgclass
  UpsertRouteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.UpsertRouteRequest").msgclass
  UpsertRouteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.UpsertRouteResponse").msgclass
  DeleteRouteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.DeleteRouteRequest").msgclass
  DeleteRouteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.DeleteRouteResponse").msgclass
  Destination = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Destination").msgclass
  CapiDiegoProcessAssociation = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.CapiDiegoProcessAssociation").msgclass
  UpsertCapiDiegoProcessAssociationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.UpsertCapiDiegoProcessAssociationRequest").msgclass
  UpsertCapiDiegoProcessAssociationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.UpsertCapiDiegoProcessAssociationResponse").msgclass
  DeleteCapiDiegoProcessAssociationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.DeleteCapiDiegoProcessAssociationRequest").msgclass
  DeleteCapiDiegoProcessAssociationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.DeleteCapiDiegoProcessAssociationResponse").msgclass
  BulkSyncRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.BulkSyncRequest").msgclass
  BulkSyncResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.BulkSyncResponse").msgclass
end
