// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	sync "sync"

	models "code.cloudfoundry.org/copilot/models"
)

type CAPIDiegoProcessAssociationsRepo struct {
	DeleteStub        func(*models.CAPIProcessGUID)
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 *models.CAPIProcessGUID
	}
	GetStub        func(*models.CAPIProcessGUID) *models.CAPIDiegoProcessAssociation
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 *models.CAPIProcessGUID
	}
	getReturns struct {
		result1 *models.CAPIDiegoProcessAssociation
	}
	getReturnsOnCall map[int]struct {
		result1 *models.CAPIDiegoProcessAssociation
	}
	ListStub        func() map[models.CAPIProcessGUID]*models.DiegoProcessGUIDs
	listMutex       sync.RWMutex
	listArgsForCall []struct {
	}
	listReturns struct {
		result1 map[models.CAPIProcessGUID]*models.DiegoProcessGUIDs
	}
	listReturnsOnCall map[int]struct {
		result1 map[models.CAPIProcessGUID]*models.DiegoProcessGUIDs
	}
	SyncStub        func([]*models.CAPIDiegoProcessAssociation)
	syncMutex       sync.RWMutex
	syncArgsForCall []struct {
		arg1 []*models.CAPIDiegoProcessAssociation
	}
	UpsertStub        func(*models.CAPIDiegoProcessAssociation)
	upsertMutex       sync.RWMutex
	upsertArgsForCall []struct {
		arg1 *models.CAPIDiegoProcessAssociation
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CAPIDiegoProcessAssociationsRepo) Delete(arg1 *models.CAPIProcessGUID) {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 *models.CAPIProcessGUID
	}{arg1})
	fake.recordInvocation("Delete", []interface{}{arg1})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		fake.DeleteStub(arg1)
	}
}

func (fake *CAPIDiegoProcessAssociationsRepo) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *CAPIDiegoProcessAssociationsRepo) DeleteCalls(stub func(*models.CAPIProcessGUID)) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *CAPIDiegoProcessAssociationsRepo) DeleteArgsForCall(i int) *models.CAPIProcessGUID {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CAPIDiegoProcessAssociationsRepo) Get(arg1 *models.CAPIProcessGUID) *models.CAPIDiegoProcessAssociation {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 *models.CAPIProcessGUID
	}{arg1})
	fake.recordInvocation("Get", []interface{}{arg1})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.getReturns
	return fakeReturns.result1
}

func (fake *CAPIDiegoProcessAssociationsRepo) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *CAPIDiegoProcessAssociationsRepo) GetCalls(stub func(*models.CAPIProcessGUID) *models.CAPIDiegoProcessAssociation) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *CAPIDiegoProcessAssociationsRepo) GetArgsForCall(i int) *models.CAPIProcessGUID {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CAPIDiegoProcessAssociationsRepo) GetReturns(result1 *models.CAPIDiegoProcessAssociation) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *models.CAPIDiegoProcessAssociation
	}{result1}
}

func (fake *CAPIDiegoProcessAssociationsRepo) GetReturnsOnCall(i int, result1 *models.CAPIDiegoProcessAssociation) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *models.CAPIDiegoProcessAssociation
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *models.CAPIDiegoProcessAssociation
	}{result1}
}

func (fake *CAPIDiegoProcessAssociationsRepo) List() map[models.CAPIProcessGUID]*models.DiegoProcessGUIDs {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
	}{})
	fake.recordInvocation("List", []interface{}{})
	fake.listMutex.Unlock()
	if fake.ListStub != nil {
		return fake.ListStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.listReturns
	return fakeReturns.result1
}

func (fake *CAPIDiegoProcessAssociationsRepo) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *CAPIDiegoProcessAssociationsRepo) ListCalls(stub func() map[models.CAPIProcessGUID]*models.DiegoProcessGUIDs) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *CAPIDiegoProcessAssociationsRepo) ListReturns(result1 map[models.CAPIProcessGUID]*models.DiegoProcessGUIDs) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 map[models.CAPIProcessGUID]*models.DiegoProcessGUIDs
	}{result1}
}

func (fake *CAPIDiegoProcessAssociationsRepo) ListReturnsOnCall(i int, result1 map[models.CAPIProcessGUID]*models.DiegoProcessGUIDs) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 map[models.CAPIProcessGUID]*models.DiegoProcessGUIDs
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 map[models.CAPIProcessGUID]*models.DiegoProcessGUIDs
	}{result1}
}

func (fake *CAPIDiegoProcessAssociationsRepo) Sync(arg1 []*models.CAPIDiegoProcessAssociation) {
	var arg1Copy []*models.CAPIDiegoProcessAssociation
	if arg1 != nil {
		arg1Copy = make([]*models.CAPIDiegoProcessAssociation, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.syncMutex.Lock()
	fake.syncArgsForCall = append(fake.syncArgsForCall, struct {
		arg1 []*models.CAPIDiegoProcessAssociation
	}{arg1Copy})
	fake.recordInvocation("Sync", []interface{}{arg1Copy})
	fake.syncMutex.Unlock()
	if fake.SyncStub != nil {
		fake.SyncStub(arg1)
	}
}

func (fake *CAPIDiegoProcessAssociationsRepo) SyncCallCount() int {
	fake.syncMutex.RLock()
	defer fake.syncMutex.RUnlock()
	return len(fake.syncArgsForCall)
}

func (fake *CAPIDiegoProcessAssociationsRepo) SyncCalls(stub func([]*models.CAPIDiegoProcessAssociation)) {
	fake.syncMutex.Lock()
	defer fake.syncMutex.Unlock()
	fake.SyncStub = stub
}

func (fake *CAPIDiegoProcessAssociationsRepo) SyncArgsForCall(i int) []*models.CAPIDiegoProcessAssociation {
	fake.syncMutex.RLock()
	defer fake.syncMutex.RUnlock()
	argsForCall := fake.syncArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CAPIDiegoProcessAssociationsRepo) Upsert(arg1 *models.CAPIDiegoProcessAssociation) {
	fake.upsertMutex.Lock()
	fake.upsertArgsForCall = append(fake.upsertArgsForCall, struct {
		arg1 *models.CAPIDiegoProcessAssociation
	}{arg1})
	fake.recordInvocation("Upsert", []interface{}{arg1})
	fake.upsertMutex.Unlock()
	if fake.UpsertStub != nil {
		fake.UpsertStub(arg1)
	}
}

func (fake *CAPIDiegoProcessAssociationsRepo) UpsertCallCount() int {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	return len(fake.upsertArgsForCall)
}

func (fake *CAPIDiegoProcessAssociationsRepo) UpsertCalls(stub func(*models.CAPIDiegoProcessAssociation)) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = stub
}

func (fake *CAPIDiegoProcessAssociationsRepo) UpsertArgsForCall(i int) *models.CAPIDiegoProcessAssociation {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	argsForCall := fake.upsertArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CAPIDiegoProcessAssociationsRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	fake.syncMutex.RLock()
	defer fake.syncMutex.RUnlock()
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CAPIDiegoProcessAssociationsRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
