// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type RoutesRepoVIPResolverInterface struct {
	GetVIPByNameStub        func(string) (string, bool)
	getVIPByNameMutex       sync.RWMutex
	getVIPByNameArgsForCall []struct {
		arg1 string
	}
	getVIPByNameReturns struct {
		result1 string
		result2 bool
	}
	getVIPByNameReturnsOnCall map[int]struct {
		result1 string
		result2 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RoutesRepoVIPResolverInterface) GetVIPByName(arg1 string) (string, bool) {
	fake.getVIPByNameMutex.Lock()
	ret, specificReturn := fake.getVIPByNameReturnsOnCall[len(fake.getVIPByNameArgsForCall)]
	fake.getVIPByNameArgsForCall = append(fake.getVIPByNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetVIPByName", []interface{}{arg1})
	fake.getVIPByNameMutex.Unlock()
	if fake.GetVIPByNameStub != nil {
		return fake.GetVIPByNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getVIPByNameReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RoutesRepoVIPResolverInterface) GetVIPByNameCallCount() int {
	fake.getVIPByNameMutex.RLock()
	defer fake.getVIPByNameMutex.RUnlock()
	return len(fake.getVIPByNameArgsForCall)
}

func (fake *RoutesRepoVIPResolverInterface) GetVIPByNameCalls(stub func(string) (string, bool)) {
	fake.getVIPByNameMutex.Lock()
	defer fake.getVIPByNameMutex.Unlock()
	fake.GetVIPByNameStub = stub
}

func (fake *RoutesRepoVIPResolverInterface) GetVIPByNameArgsForCall(i int) string {
	fake.getVIPByNameMutex.RLock()
	defer fake.getVIPByNameMutex.RUnlock()
	argsForCall := fake.getVIPByNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *RoutesRepoVIPResolverInterface) GetVIPByNameReturns(result1 string, result2 bool) {
	fake.getVIPByNameMutex.Lock()
	defer fake.getVIPByNameMutex.Unlock()
	fake.GetVIPByNameStub = nil
	fake.getVIPByNameReturns = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *RoutesRepoVIPResolverInterface) GetVIPByNameReturnsOnCall(i int, result1 string, result2 bool) {
	fake.getVIPByNameMutex.Lock()
	defer fake.getVIPByNameMutex.Unlock()
	fake.GetVIPByNameStub = nil
	if fake.getVIPByNameReturnsOnCall == nil {
		fake.getVIPByNameReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
		})
	}
	fake.getVIPByNameReturnsOnCall[i] = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *RoutesRepoVIPResolverInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getVIPByNameMutex.RLock()
	defer fake.getVIPByNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RoutesRepoVIPResolverInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
