// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	HealthRequest
	HealthResponse
	RoutesRequest
	RoutesResponse
	BackendSet
	Backend
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthRequest struct {
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HealthResponse struct {
	Healthy bool `protobuf:"varint,1,opt,name=healthy" json:"healthy,omitempty"`
}

func (m *HealthResponse) Reset()                    { *m = HealthResponse{} }
func (m *HealthResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()               {}
func (*HealthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HealthResponse) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

type RoutesRequest struct {
}

func (m *RoutesRequest) Reset()                    { *m = RoutesRequest{} }
func (m *RoutesRequest) String() string            { return proto.CompactTextString(m) }
func (*RoutesRequest) ProtoMessage()               {}
func (*RoutesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type RoutesResponse struct {
	// key is hostname
	Backends map[string]*BackendSet `protobuf:"bytes,1,rep,name=backends" json:"backends,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RoutesResponse) Reset()                    { *m = RoutesResponse{} }
func (m *RoutesResponse) String() string            { return proto.CompactTextString(m) }
func (*RoutesResponse) ProtoMessage()               {}
func (*RoutesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RoutesResponse) GetBackends() map[string]*BackendSet {
	if m != nil {
		return m.Backends
	}
	return nil
}

type BackendSet struct {
	Backends []*Backend `protobuf:"bytes,1,rep,name=backends" json:"backends,omitempty"`
}

func (m *BackendSet) Reset()                    { *m = BackendSet{} }
func (m *BackendSet) String() string            { return proto.CompactTextString(m) }
func (*BackendSet) ProtoMessage()               {}
func (*BackendSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BackendSet) GetBackends() []*Backend {
	if m != nil {
		return m.Backends
	}
	return nil
}

type Backend struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Port    uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *Backend) Reset()                    { *m = Backend{} }
func (m *Backend) String() string            { return proto.CompactTextString(m) }
func (*Backend) ProtoMessage()               {}
func (*Backend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Backend) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Backend) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*HealthRequest)(nil), "api.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "api.HealthResponse")
	proto.RegisterType((*RoutesRequest)(nil), "api.RoutesRequest")
	proto.RegisterType((*RoutesResponse)(nil), "api.RoutesResponse")
	proto.RegisterType((*BackendSet)(nil), "api.BackendSet")
	proto.RegisterType((*Backend)(nil), "api.Backend")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Copilot service

type CopilotClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Routes(ctx context.Context, in *RoutesRequest, opts ...grpc.CallOption) (*RoutesResponse, error)
}

type copilotClient struct {
	cc *grpc.ClientConn
}

func NewCopilotClient(cc *grpc.ClientConn) CopilotClient {
	return &copilotClient{cc}
}

func (c *copilotClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := grpc.Invoke(ctx, "/api.Copilot/Health", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copilotClient) Routes(ctx context.Context, in *RoutesRequest, opts ...grpc.CallOption) (*RoutesResponse, error) {
	out := new(RoutesResponse)
	err := grpc.Invoke(ctx, "/api.Copilot/Routes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Copilot service

type CopilotServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Routes(context.Context, *RoutesRequest) (*RoutesResponse, error)
}

func RegisterCopilotServer(s *grpc.Server, srv CopilotServer) {
	s.RegisterService(&_Copilot_serviceDesc, srv)
}

func _Copilot_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopilotServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Copilot/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopilotServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Copilot_Routes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopilotServer).Routes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Copilot/Routes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopilotServer).Routes(ctx, req.(*RoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Copilot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Copilot",
	HandlerType: (*CopilotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Copilot_Health_Handler,
		},
		{
			MethodName: "Routes",
			Handler:    _Copilot_Routes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0xf3, 0x30,
	0x18, 0xc7, 0x97, 0xf5, 0x7d, 0xd7, 0xed, 0x99, 0xdd, 0x24, 0x5e, 0xca, 0x4e, 0x35, 0x20, 0x14,
	0x0f, 0x3d, 0x74, 0xa0, 0x22, 0x78, 0x51, 0x04, 0x0f, 0x9e, 0xe2, 0x27, 0xc8, 0xec, 0x03, 0x2b,
	0x2b, 0x4d, 0x6c, 0x52, 0x61, 0x1f, 0xc6, 0xef, 0x2a, 0x4d, 0x13, 0x67, 0xf0, 0x96, 0xfc, 0x9f,
	0xe7, 0xd7, 0xfe, 0xf9, 0x05, 0x16, 0x42, 0xd5, 0x85, 0xea, 0xa4, 0x91, 0x34, 0x12, 0xaa, 0x66,
	0x6b, 0x48, 0x5e, 0x50, 0x34, 0x66, 0xcf, 0xf1, 0xa3, 0x47, 0x6d, 0xd8, 0x35, 0xac, 0x7c, 0xa0,
	0x95, 0x6c, 0x35, 0xd2, 0x14, 0xe2, 0xbd, 0x4d, 0x8e, 0x29, 0xc9, 0x48, 0x3e, 0xe7, 0xfe, 0x3a,
	0xc0, 0x5c, 0xf6, 0x06, 0xb5, 0x87, 0xbf, 0x08, 0xac, 0x7c, 0xe2, 0xe8, 0x07, 0x98, 0xef, 0xc4,
	0xfb, 0x01, 0xdb, 0x4a, 0xa7, 0x24, 0x8b, 0xf2, 0x65, 0x79, 0x59, 0x0c, 0x1d, 0xc2, 0xb5, 0xe2,
	0xd1, 0xed, 0x3c, 0xb7, 0xa6, 0x3b, 0xf2, 0x1f, 0x64, 0xf3, 0x0a, 0x49, 0x30, 0xa2, 0xe7, 0x10,
	0x1d, 0x70, 0x6c, 0xb2, 0xe0, 0xc3, 0x91, 0x5e, 0xc1, 0xff, 0x4f, 0xd1, 0xf4, 0x98, 0x4e, 0x33,
	0x92, 0x2f, 0xcb, 0xb5, 0xfd, 0xbc, 0x83, 0xde, 0xd0, 0xf0, 0x71, 0x7a, 0x3f, 0xbd, 0x23, 0xec,
	0x06, 0xe0, 0x34, 0xa0, 0xf9, 0x9f, 0x6a, 0x67, 0xbf, 0xd9, 0x53, 0x0b, 0x76, 0x0b, 0xb1, 0x0b,
	0x07, 0x1b, 0xa2, 0xaa, 0x3a, 0xd4, 0xda, 0x75, 0xf0, 0x57, 0x4a, 0xe1, 0x9f, 0x92, 0x9d, 0xb1,
	0x35, 0x12, 0x6e, 0xcf, 0xa5, 0x86, 0xf8, 0x49, 0xaa, 0xba, 0x91, 0x86, 0x6e, 0x61, 0x36, 0x8a,
	0xa5, 0xd4, 0xfe, 0x25, 0xd0, 0xbe, 0xb9, 0x08, 0xb2, 0x51, 0x0a, 0x9b, 0x0c, 0xd0, 0x28, 0xca,
	0x41, 0x81, 0x6e, 0x07, 0x85, 0x26, 0xd9, 0x64, 0x37, 0xb3, 0xef, 0xbb, 0xfd, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x57, 0x7e, 0x58, 0x2c, 0xec, 0x01, 0x00, 0x00,
}
