// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloud_controller.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListCfRoutesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCfRoutesRequest) Reset()         { *m = ListCfRoutesRequest{} }
func (m *ListCfRoutesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCfRoutesRequest) ProtoMessage()    {}
func (*ListCfRoutesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{0}
}
func (m *ListCfRoutesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCfRoutesRequest.Unmarshal(m, b)
}
func (m *ListCfRoutesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCfRoutesRequest.Marshal(b, m, deterministic)
}
func (dst *ListCfRoutesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCfRoutesRequest.Merge(dst, src)
}
func (m *ListCfRoutesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCfRoutesRequest.Size(m)
}
func (m *ListCfRoutesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCfRoutesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCfRoutesRequest proto.InternalMessageInfo

type ListCfRoutesResponse struct {
	// key is route guid
	// value is host
	Routes               map[string]string `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListCfRoutesResponse) Reset()         { *m = ListCfRoutesResponse{} }
func (m *ListCfRoutesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCfRoutesResponse) ProtoMessage()    {}
func (*ListCfRoutesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{1}
}
func (m *ListCfRoutesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCfRoutesResponse.Unmarshal(m, b)
}
func (m *ListCfRoutesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCfRoutesResponse.Marshal(b, m, deterministic)
}
func (dst *ListCfRoutesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCfRoutesResponse.Merge(dst, src)
}
func (m *ListCfRoutesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCfRoutesResponse.Size(m)
}
func (m *ListCfRoutesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCfRoutesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCfRoutesResponse proto.InternalMessageInfo

func (m *ListCfRoutesResponse) GetRoutes() map[string]string {
	if m != nil {
		return m.Routes
	}
	return nil
}

type ListCapiDiegoProcessAssociationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCapiDiegoProcessAssociationsRequest) Reset() {
	*m = ListCapiDiegoProcessAssociationsRequest{}
}
func (m *ListCapiDiegoProcessAssociationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCapiDiegoProcessAssociationsRequest) ProtoMessage()    {}
func (*ListCapiDiegoProcessAssociationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{2}
}
func (m *ListCapiDiegoProcessAssociationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCapiDiegoProcessAssociationsRequest.Unmarshal(m, b)
}
func (m *ListCapiDiegoProcessAssociationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCapiDiegoProcessAssociationsRequest.Marshal(b, m, deterministic)
}
func (dst *ListCapiDiegoProcessAssociationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCapiDiegoProcessAssociationsRequest.Merge(dst, src)
}
func (m *ListCapiDiegoProcessAssociationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCapiDiegoProcessAssociationsRequest.Size(m)
}
func (m *ListCapiDiegoProcessAssociationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCapiDiegoProcessAssociationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCapiDiegoProcessAssociationsRequest proto.InternalMessageInfo

// this is only for ListCapiDiegoProcessAssociationsResponse,
// since protobuf does not support list values in maps.
// it's gross. try not to use it.
type DiegoProcessGuids struct {
	DiegoProcessGuids    []string `protobuf:"bytes,1,rep,name=diego_process_guids,json=diegoProcessGuids,proto3" json:"diego_process_guids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiegoProcessGuids) Reset()         { *m = DiegoProcessGuids{} }
func (m *DiegoProcessGuids) String() string { return proto.CompactTextString(m) }
func (*DiegoProcessGuids) ProtoMessage()    {}
func (*DiegoProcessGuids) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{3}
}
func (m *DiegoProcessGuids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiegoProcessGuids.Unmarshal(m, b)
}
func (m *DiegoProcessGuids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiegoProcessGuids.Marshal(b, m, deterministic)
}
func (dst *DiegoProcessGuids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiegoProcessGuids.Merge(dst, src)
}
func (m *DiegoProcessGuids) XXX_Size() int {
	return xxx_messageInfo_DiegoProcessGuids.Size(m)
}
func (m *DiegoProcessGuids) XXX_DiscardUnknown() {
	xxx_messageInfo_DiegoProcessGuids.DiscardUnknown(m)
}

var xxx_messageInfo_DiegoProcessGuids proto.InternalMessageInfo

func (m *DiegoProcessGuids) GetDiegoProcessGuids() []string {
	if m != nil {
		return m.DiegoProcessGuids
	}
	return nil
}

type ListCapiDiegoProcessAssociationsResponse struct {
	// key is capi process guid
	// value is a list of diego process guids
	CapiDiegoProcessAssociations map[string]*DiegoProcessGuids `protobuf:"bytes,1,rep,name=capi_diego_process_associations,json=capiDiegoProcessAssociations,proto3" json:"capi_diego_process_associations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral         struct{}                      `json:"-"`
	XXX_unrecognized             []byte                        `json:"-"`
	XXX_sizecache                int32                         `json:"-"`
}

func (m *ListCapiDiegoProcessAssociationsResponse) Reset() {
	*m = ListCapiDiegoProcessAssociationsResponse{}
}
func (m *ListCapiDiegoProcessAssociationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCapiDiegoProcessAssociationsResponse) ProtoMessage()    {}
func (*ListCapiDiegoProcessAssociationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{4}
}
func (m *ListCapiDiegoProcessAssociationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCapiDiegoProcessAssociationsResponse.Unmarshal(m, b)
}
func (m *ListCapiDiegoProcessAssociationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCapiDiegoProcessAssociationsResponse.Marshal(b, m, deterministic)
}
func (dst *ListCapiDiegoProcessAssociationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCapiDiegoProcessAssociationsResponse.Merge(dst, src)
}
func (m *ListCapiDiegoProcessAssociationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCapiDiegoProcessAssociationsResponse.Size(m)
}
func (m *ListCapiDiegoProcessAssociationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCapiDiegoProcessAssociationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCapiDiegoProcessAssociationsResponse proto.InternalMessageInfo

func (m *ListCapiDiegoProcessAssociationsResponse) GetCapiDiegoProcessAssociations() map[string]*DiegoProcessGuids {
	if m != nil {
		return m.CapiDiegoProcessAssociations
	}
	return nil
}

type Route struct {
	Guid                 string         `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Host                 string         `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Path                 string         `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Destinations         []*Destination `protobuf:"bytes,4,rep,name=destinations,proto3" json:"destinations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{5}
}
func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (dst *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(dst, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Route) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Route) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Route) GetDestinations() []*Destination {
	if m != nil {
		return m.Destinations
	}
	return nil
}

type UpsertRouteRequest struct {
	Route                *Route   `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertRouteRequest) Reset()         { *m = UpsertRouteRequest{} }
func (m *UpsertRouteRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertRouteRequest) ProtoMessage()    {}
func (*UpsertRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{6}
}
func (m *UpsertRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertRouteRequest.Unmarshal(m, b)
}
func (m *UpsertRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertRouteRequest.Marshal(b, m, deterministic)
}
func (dst *UpsertRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertRouteRequest.Merge(dst, src)
}
func (m *UpsertRouteRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertRouteRequest.Size(m)
}
func (m *UpsertRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertRouteRequest proto.InternalMessageInfo

func (m *UpsertRouteRequest) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type UpsertRouteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertRouteResponse) Reset()         { *m = UpsertRouteResponse{} }
func (m *UpsertRouteResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertRouteResponse) ProtoMessage()    {}
func (*UpsertRouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{7}
}
func (m *UpsertRouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertRouteResponse.Unmarshal(m, b)
}
func (m *UpsertRouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertRouteResponse.Marshal(b, m, deterministic)
}
func (dst *UpsertRouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertRouteResponse.Merge(dst, src)
}
func (m *UpsertRouteResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertRouteResponse.Size(m)
}
func (m *UpsertRouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertRouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertRouteResponse proto.InternalMessageInfo

type DeleteRouteRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRouteRequest) Reset()         { *m = DeleteRouteRequest{} }
func (m *DeleteRouteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRouteRequest) ProtoMessage()    {}
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{8}
}
func (m *DeleteRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRouteRequest.Unmarshal(m, b)
}
func (m *DeleteRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRouteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRouteRequest.Merge(dst, src)
}
func (m *DeleteRouteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRouteRequest.Size(m)
}
func (m *DeleteRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRouteRequest proto.InternalMessageInfo

func (m *DeleteRouteRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type DeleteRouteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRouteResponse) Reset()         { *m = DeleteRouteResponse{} }
func (m *DeleteRouteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRouteResponse) ProtoMessage()    {}
func (*DeleteRouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{9}
}
func (m *DeleteRouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRouteResponse.Unmarshal(m, b)
}
func (m *DeleteRouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRouteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteRouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRouteResponse.Merge(dst, src)
}
func (m *DeleteRouteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRouteResponse.Size(m)
}
func (m *DeleteRouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRouteResponse proto.InternalMessageInfo

type Destination struct {
	CapiProcessGuid      string   `protobuf:"bytes,1,opt,name=capi_process_guid,json=capiProcessGuid,proto3" json:"capi_process_guid,omitempty"`
	Weight               uint32   `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Destination) Reset()         { *m = Destination{} }
func (m *Destination) String() string { return proto.CompactTextString(m) }
func (*Destination) ProtoMessage()    {}
func (*Destination) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{10}
}
func (m *Destination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Destination.Unmarshal(m, b)
}
func (m *Destination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Destination.Marshal(b, m, deterministic)
}
func (dst *Destination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Destination.Merge(dst, src)
}
func (m *Destination) XXX_Size() int {
	return xxx_messageInfo_Destination.Size(m)
}
func (m *Destination) XXX_DiscardUnknown() {
	xxx_messageInfo_Destination.DiscardUnknown(m)
}

var xxx_messageInfo_Destination proto.InternalMessageInfo

func (m *Destination) GetCapiProcessGuid() string {
	if m != nil {
		return m.CapiProcessGuid
	}
	return ""
}

func (m *Destination) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Destination) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type CapiDiegoProcessAssociation struct {
	CapiProcessGuid      string   `protobuf:"bytes,1,opt,name=capi_process_guid,json=capiProcessGuid,proto3" json:"capi_process_guid,omitempty"`
	DiegoProcessGuids    []string `protobuf:"bytes,2,rep,name=diego_process_guids,json=diegoProcessGuids,proto3" json:"diego_process_guids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CapiDiegoProcessAssociation) Reset()         { *m = CapiDiegoProcessAssociation{} }
func (m *CapiDiegoProcessAssociation) String() string { return proto.CompactTextString(m) }
func (*CapiDiegoProcessAssociation) ProtoMessage()    {}
func (*CapiDiegoProcessAssociation) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{11}
}
func (m *CapiDiegoProcessAssociation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapiDiegoProcessAssociation.Unmarshal(m, b)
}
func (m *CapiDiegoProcessAssociation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapiDiegoProcessAssociation.Marshal(b, m, deterministic)
}
func (dst *CapiDiegoProcessAssociation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapiDiegoProcessAssociation.Merge(dst, src)
}
func (m *CapiDiegoProcessAssociation) XXX_Size() int {
	return xxx_messageInfo_CapiDiegoProcessAssociation.Size(m)
}
func (m *CapiDiegoProcessAssociation) XXX_DiscardUnknown() {
	xxx_messageInfo_CapiDiegoProcessAssociation.DiscardUnknown(m)
}

var xxx_messageInfo_CapiDiegoProcessAssociation proto.InternalMessageInfo

func (m *CapiDiegoProcessAssociation) GetCapiProcessGuid() string {
	if m != nil {
		return m.CapiProcessGuid
	}
	return ""
}

func (m *CapiDiegoProcessAssociation) GetDiegoProcessGuids() []string {
	if m != nil {
		return m.DiegoProcessGuids
	}
	return nil
}

type UpsertCapiDiegoProcessAssociationRequest struct {
	CapiDiegoProcessAssociation *CapiDiegoProcessAssociation `protobuf:"bytes,1,opt,name=capi_diego_process_association,json=capiDiegoProcessAssociation,proto3" json:"capi_diego_process_association,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                     `json:"-"`
	XXX_unrecognized            []byte                       `json:"-"`
	XXX_sizecache               int32                        `json:"-"`
}

func (m *UpsertCapiDiegoProcessAssociationRequest) Reset() {
	*m = UpsertCapiDiegoProcessAssociationRequest{}
}
func (m *UpsertCapiDiegoProcessAssociationRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertCapiDiegoProcessAssociationRequest) ProtoMessage()    {}
func (*UpsertCapiDiegoProcessAssociationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{12}
}
func (m *UpsertCapiDiegoProcessAssociationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertCapiDiegoProcessAssociationRequest.Unmarshal(m, b)
}
func (m *UpsertCapiDiegoProcessAssociationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertCapiDiegoProcessAssociationRequest.Marshal(b, m, deterministic)
}
func (dst *UpsertCapiDiegoProcessAssociationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertCapiDiegoProcessAssociationRequest.Merge(dst, src)
}
func (m *UpsertCapiDiegoProcessAssociationRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertCapiDiegoProcessAssociationRequest.Size(m)
}
func (m *UpsertCapiDiegoProcessAssociationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertCapiDiegoProcessAssociationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertCapiDiegoProcessAssociationRequest proto.InternalMessageInfo

func (m *UpsertCapiDiegoProcessAssociationRequest) GetCapiDiegoProcessAssociation() *CapiDiegoProcessAssociation {
	if m != nil {
		return m.CapiDiegoProcessAssociation
	}
	return nil
}

type UpsertCapiDiegoProcessAssociationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertCapiDiegoProcessAssociationResponse) Reset() {
	*m = UpsertCapiDiegoProcessAssociationResponse{}
}
func (m *UpsertCapiDiegoProcessAssociationResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertCapiDiegoProcessAssociationResponse) ProtoMessage()    {}
func (*UpsertCapiDiegoProcessAssociationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{13}
}
func (m *UpsertCapiDiegoProcessAssociationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertCapiDiegoProcessAssociationResponse.Unmarshal(m, b)
}
func (m *UpsertCapiDiegoProcessAssociationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertCapiDiegoProcessAssociationResponse.Marshal(b, m, deterministic)
}
func (dst *UpsertCapiDiegoProcessAssociationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertCapiDiegoProcessAssociationResponse.Merge(dst, src)
}
func (m *UpsertCapiDiegoProcessAssociationResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertCapiDiegoProcessAssociationResponse.Size(m)
}
func (m *UpsertCapiDiegoProcessAssociationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertCapiDiegoProcessAssociationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertCapiDiegoProcessAssociationResponse proto.InternalMessageInfo

type DeleteCapiDiegoProcessAssociationRequest struct {
	CapiProcessGuid      string   `protobuf:"bytes,1,opt,name=capi_process_guid,json=capiProcessGuid,proto3" json:"capi_process_guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCapiDiegoProcessAssociationRequest) Reset() {
	*m = DeleteCapiDiegoProcessAssociationRequest{}
}
func (m *DeleteCapiDiegoProcessAssociationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCapiDiegoProcessAssociationRequest) ProtoMessage()    {}
func (*DeleteCapiDiegoProcessAssociationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{14}
}
func (m *DeleteCapiDiegoProcessAssociationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCapiDiegoProcessAssociationRequest.Unmarshal(m, b)
}
func (m *DeleteCapiDiegoProcessAssociationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCapiDiegoProcessAssociationRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCapiDiegoProcessAssociationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCapiDiegoProcessAssociationRequest.Merge(dst, src)
}
func (m *DeleteCapiDiegoProcessAssociationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCapiDiegoProcessAssociationRequest.Size(m)
}
func (m *DeleteCapiDiegoProcessAssociationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCapiDiegoProcessAssociationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCapiDiegoProcessAssociationRequest proto.InternalMessageInfo

func (m *DeleteCapiDiegoProcessAssociationRequest) GetCapiProcessGuid() string {
	if m != nil {
		return m.CapiProcessGuid
	}
	return ""
}

type DeleteCapiDiegoProcessAssociationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCapiDiegoProcessAssociationResponse) Reset() {
	*m = DeleteCapiDiegoProcessAssociationResponse{}
}
func (m *DeleteCapiDiegoProcessAssociationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCapiDiegoProcessAssociationResponse) ProtoMessage()    {}
func (*DeleteCapiDiegoProcessAssociationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{15}
}
func (m *DeleteCapiDiegoProcessAssociationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCapiDiegoProcessAssociationResponse.Unmarshal(m, b)
}
func (m *DeleteCapiDiegoProcessAssociationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCapiDiegoProcessAssociationResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteCapiDiegoProcessAssociationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCapiDiegoProcessAssociationResponse.Merge(dst, src)
}
func (m *DeleteCapiDiegoProcessAssociationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCapiDiegoProcessAssociationResponse.Size(m)
}
func (m *DeleteCapiDiegoProcessAssociationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCapiDiegoProcessAssociationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCapiDiegoProcessAssociationResponse proto.InternalMessageInfo

type BulkSyncRequest struct {
	Routes                       []*Route                       `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	CapiDiegoProcessAssociations []*CapiDiegoProcessAssociation `protobuf:"bytes,3,rep,name=capi_diego_process_associations,json=capiDiegoProcessAssociations,proto3" json:"capi_diego_process_associations,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                       `json:"-"`
	XXX_unrecognized             []byte                         `json:"-"`
	XXX_sizecache                int32                          `json:"-"`
}

func (m *BulkSyncRequest) Reset()         { *m = BulkSyncRequest{} }
func (m *BulkSyncRequest) String() string { return proto.CompactTextString(m) }
func (*BulkSyncRequest) ProtoMessage()    {}
func (*BulkSyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{16}
}
func (m *BulkSyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkSyncRequest.Unmarshal(m, b)
}
func (m *BulkSyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkSyncRequest.Marshal(b, m, deterministic)
}
func (dst *BulkSyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkSyncRequest.Merge(dst, src)
}
func (m *BulkSyncRequest) XXX_Size() int {
	return xxx_messageInfo_BulkSyncRequest.Size(m)
}
func (m *BulkSyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkSyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkSyncRequest proto.InternalMessageInfo

func (m *BulkSyncRequest) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *BulkSyncRequest) GetCapiDiegoProcessAssociations() []*CapiDiegoProcessAssociation {
	if m != nil {
		return m.CapiDiegoProcessAssociations
	}
	return nil
}

type BulkSyncResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkSyncResponse) Reset()         { *m = BulkSyncResponse{} }
func (m *BulkSyncResponse) String() string { return proto.CompactTextString(m) }
func (*BulkSyncResponse) ProtoMessage()    {}
func (*BulkSyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloud_controller_ca208ef4d264831a, []int{17}
}
func (m *BulkSyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkSyncResponse.Unmarshal(m, b)
}
func (m *BulkSyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkSyncResponse.Marshal(b, m, deterministic)
}
func (dst *BulkSyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkSyncResponse.Merge(dst, src)
}
func (m *BulkSyncResponse) XXX_Size() int {
	return xxx_messageInfo_BulkSyncResponse.Size(m)
}
func (m *BulkSyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkSyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkSyncResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListCfRoutesRequest)(nil), "api.ListCfRoutesRequest")
	proto.RegisterType((*ListCfRoutesResponse)(nil), "api.ListCfRoutesResponse")
	proto.RegisterMapType((map[string]string)(nil), "api.ListCfRoutesResponse.RoutesEntry")
	proto.RegisterType((*ListCapiDiegoProcessAssociationsRequest)(nil), "api.ListCapiDiegoProcessAssociationsRequest")
	proto.RegisterType((*DiegoProcessGuids)(nil), "api.DiegoProcessGuids")
	proto.RegisterType((*ListCapiDiegoProcessAssociationsResponse)(nil), "api.ListCapiDiegoProcessAssociationsResponse")
	proto.RegisterMapType((map[string]*DiegoProcessGuids)(nil), "api.ListCapiDiegoProcessAssociationsResponse.CapiDiegoProcessAssociationsEntry")
	proto.RegisterType((*Route)(nil), "api.Route")
	proto.RegisterType((*UpsertRouteRequest)(nil), "api.UpsertRouteRequest")
	proto.RegisterType((*UpsertRouteResponse)(nil), "api.UpsertRouteResponse")
	proto.RegisterType((*DeleteRouteRequest)(nil), "api.DeleteRouteRequest")
	proto.RegisterType((*DeleteRouteResponse)(nil), "api.DeleteRouteResponse")
	proto.RegisterType((*Destination)(nil), "api.Destination")
	proto.RegisterType((*CapiDiegoProcessAssociation)(nil), "api.CapiDiegoProcessAssociation")
	proto.RegisterType((*UpsertCapiDiegoProcessAssociationRequest)(nil), "api.UpsertCapiDiegoProcessAssociationRequest")
	proto.RegisterType((*UpsertCapiDiegoProcessAssociationResponse)(nil), "api.UpsertCapiDiegoProcessAssociationResponse")
	proto.RegisterType((*DeleteCapiDiegoProcessAssociationRequest)(nil), "api.DeleteCapiDiegoProcessAssociationRequest")
	proto.RegisterType((*DeleteCapiDiegoProcessAssociationResponse)(nil), "api.DeleteCapiDiegoProcessAssociationResponse")
	proto.RegisterType((*BulkSyncRequest)(nil), "api.BulkSyncRequest")
	proto.RegisterType((*BulkSyncResponse)(nil), "api.BulkSyncResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CloudControllerCopilotClient is the client API for CloudControllerCopilot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CloudControllerCopilotClient interface {
	ListCfRoutes(ctx context.Context, in *ListCfRoutesRequest, opts ...grpc.CallOption) (*ListCfRoutesResponse, error)
	ListCapiDiegoProcessAssociations(ctx context.Context, in *ListCapiDiegoProcessAssociationsRequest, opts ...grpc.CallOption) (*ListCapiDiegoProcessAssociationsResponse, error)
	UpsertRoute(ctx context.Context, in *UpsertRouteRequest, opts ...grpc.CallOption) (*UpsertRouteResponse, error)
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error)
	UpsertCapiDiegoProcessAssociation(ctx context.Context, in *UpsertCapiDiegoProcessAssociationRequest, opts ...grpc.CallOption) (*UpsertCapiDiegoProcessAssociationResponse, error)
	DeleteCapiDiegoProcessAssociation(ctx context.Context, in *DeleteCapiDiegoProcessAssociationRequest, opts ...grpc.CallOption) (*DeleteCapiDiegoProcessAssociationResponse, error)
	BulkSync(ctx context.Context, in *BulkSyncRequest, opts ...grpc.CallOption) (*BulkSyncResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type cloudControllerCopilotClient struct {
	cc *grpc.ClientConn
}

func NewCloudControllerCopilotClient(cc *grpc.ClientConn) CloudControllerCopilotClient {
	return &cloudControllerCopilotClient{cc}
}

func (c *cloudControllerCopilotClient) ListCfRoutes(ctx context.Context, in *ListCfRoutesRequest, opts ...grpc.CallOption) (*ListCfRoutesResponse, error) {
	out := new(ListCfRoutesResponse)
	err := c.cc.Invoke(ctx, "/api.CloudControllerCopilot/ListCfRoutes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) ListCapiDiegoProcessAssociations(ctx context.Context, in *ListCapiDiegoProcessAssociationsRequest, opts ...grpc.CallOption) (*ListCapiDiegoProcessAssociationsResponse, error) {
	out := new(ListCapiDiegoProcessAssociationsResponse)
	err := c.cc.Invoke(ctx, "/api.CloudControllerCopilot/ListCapiDiegoProcessAssociations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) UpsertRoute(ctx context.Context, in *UpsertRouteRequest, opts ...grpc.CallOption) (*UpsertRouteResponse, error) {
	out := new(UpsertRouteResponse)
	err := c.cc.Invoke(ctx, "/api.CloudControllerCopilot/UpsertRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error) {
	out := new(DeleteRouteResponse)
	err := c.cc.Invoke(ctx, "/api.CloudControllerCopilot/DeleteRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) UpsertCapiDiegoProcessAssociation(ctx context.Context, in *UpsertCapiDiegoProcessAssociationRequest, opts ...grpc.CallOption) (*UpsertCapiDiegoProcessAssociationResponse, error) {
	out := new(UpsertCapiDiegoProcessAssociationResponse)
	err := c.cc.Invoke(ctx, "/api.CloudControllerCopilot/UpsertCapiDiegoProcessAssociation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) DeleteCapiDiegoProcessAssociation(ctx context.Context, in *DeleteCapiDiegoProcessAssociationRequest, opts ...grpc.CallOption) (*DeleteCapiDiegoProcessAssociationResponse, error) {
	out := new(DeleteCapiDiegoProcessAssociationResponse)
	err := c.cc.Invoke(ctx, "/api.CloudControllerCopilot/DeleteCapiDiegoProcessAssociation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) BulkSync(ctx context.Context, in *BulkSyncRequest, opts ...grpc.CallOption) (*BulkSyncResponse, error) {
	out := new(BulkSyncResponse)
	err := c.cc.Invoke(ctx, "/api.CloudControllerCopilot/BulkSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/api.CloudControllerCopilot/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudControllerCopilotServer is the server API for CloudControllerCopilot service.
type CloudControllerCopilotServer interface {
	ListCfRoutes(context.Context, *ListCfRoutesRequest) (*ListCfRoutesResponse, error)
	ListCapiDiegoProcessAssociations(context.Context, *ListCapiDiegoProcessAssociationsRequest) (*ListCapiDiegoProcessAssociationsResponse, error)
	UpsertRoute(context.Context, *UpsertRouteRequest) (*UpsertRouteResponse, error)
	DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error)
	UpsertCapiDiegoProcessAssociation(context.Context, *UpsertCapiDiegoProcessAssociationRequest) (*UpsertCapiDiegoProcessAssociationResponse, error)
	DeleteCapiDiegoProcessAssociation(context.Context, *DeleteCapiDiegoProcessAssociationRequest) (*DeleteCapiDiegoProcessAssociationResponse, error)
	BulkSync(context.Context, *BulkSyncRequest) (*BulkSyncResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

func RegisterCloudControllerCopilotServer(s *grpc.Server, srv CloudControllerCopilotServer) {
	s.RegisterService(&_CloudControllerCopilot_serviceDesc, srv)
}

func _CloudControllerCopilot_ListCfRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCfRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).ListCfRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/ListCfRoutes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).ListCfRoutes(ctx, req.(*ListCfRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_ListCapiDiegoProcessAssociations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCapiDiegoProcessAssociationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).ListCapiDiegoProcessAssociations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/ListCapiDiegoProcessAssociations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).ListCapiDiegoProcessAssociations(ctx, req.(*ListCapiDiegoProcessAssociationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_UpsertRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).UpsertRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/UpsertRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).UpsertRoute(ctx, req.(*UpsertRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/DeleteRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_UpsertCapiDiegoProcessAssociation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCapiDiegoProcessAssociationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).UpsertCapiDiegoProcessAssociation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/UpsertCapiDiegoProcessAssociation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).UpsertCapiDiegoProcessAssociation(ctx, req.(*UpsertCapiDiegoProcessAssociationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_DeleteCapiDiegoProcessAssociation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCapiDiegoProcessAssociationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).DeleteCapiDiegoProcessAssociation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/DeleteCapiDiegoProcessAssociation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).DeleteCapiDiegoProcessAssociation(ctx, req.(*DeleteCapiDiegoProcessAssociationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_BulkSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).BulkSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/BulkSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).BulkSync(ctx, req.(*BulkSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudControllerCopilot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CloudControllerCopilot",
	HandlerType: (*CloudControllerCopilotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCfRoutes",
			Handler:    _CloudControllerCopilot_ListCfRoutes_Handler,
		},
		{
			MethodName: "ListCapiDiegoProcessAssociations",
			Handler:    _CloudControllerCopilot_ListCapiDiegoProcessAssociations_Handler,
		},
		{
			MethodName: "UpsertRoute",
			Handler:    _CloudControllerCopilot_UpsertRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _CloudControllerCopilot_DeleteRoute_Handler,
		},
		{
			MethodName: "UpsertCapiDiegoProcessAssociation",
			Handler:    _CloudControllerCopilot_UpsertCapiDiegoProcessAssociation_Handler,
		},
		{
			MethodName: "DeleteCapiDiegoProcessAssociation",
			Handler:    _CloudControllerCopilot_DeleteCapiDiegoProcessAssociation_Handler,
		},
		{
			MethodName: "BulkSync",
			Handler:    _CloudControllerCopilot_BulkSync_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CloudControllerCopilot_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud_controller.proto",
}

func init() {
	proto.RegisterFile("cloud_controller.proto", fileDescriptor_cloud_controller_ca208ef4d264831a)
}

var fileDescriptor_cloud_controller_ca208ef4d264831a = []byte{
	// 733 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0x93, 0x26, 0x6a, 0x27, 0xed, 0xdf, 0x74, 0xda, 0xe6, 0x0f, 0x2e, 0x82, 0xd4, 0x12,
	0x22, 0x85, 0xd6, 0x87, 0x14, 0x21, 0x8a, 0xc4, 0x81, 0xa6, 0x15, 0x08, 0x21, 0x81, 0x8c, 0xe0,
	0x1a, 0x19, 0x67, 0x49, 0xac, 0xba, 0x5e, 0xe3, 0xdd, 0x80, 0x72, 0x44, 0xe2, 0x01, 0xe0, 0xc2,
	0x53, 0x70, 0xe4, 0xa5, 0x78, 0x0b, 0xe4, 0xdd, 0x4d, 0xba, 0x6e, 0x52, 0xdb, 0xb9, 0xad, 0x67,
	0x67, 0xbe, 0xf9, 0xf6, 0x9b, 0xd9, 0x59, 0x43, 0xd3, 0x0b, 0xe8, 0x78, 0xd0, 0xf7, 0x68, 0xc8,
	0x63, 0x1a, 0x04, 0x24, 0xb6, 0xa3, 0x98, 0x72, 0x8a, 0x15, 0x37, 0xf2, 0xcd, 0x75, 0x8f, 0x5e,
	0x5e, 0xd2, 0x50, 0x9a, 0xac, 0x5d, 0xd8, 0x7e, 0xed, 0x33, 0xde, 0xfb, 0xe4, 0xd0, 0x31, 0x27,
	0xcc, 0x21, 0x9f, 0xc7, 0x84, 0x71, 0xeb, 0x87, 0x01, 0x3b, 0x69, 0x3b, 0x8b, 0x68, 0xc8, 0x08,
	0x3e, 0x83, 0x5a, 0x2c, 0x2c, 0x2d, 0xa3, 0x5d, 0xe9, 0xd4, 0xbb, 0xf7, 0x6c, 0x37, 0xf2, 0xed,
	0x45, 0xae, 0xb6, 0xfc, 0x3c, 0x0f, 0x79, 0x3c, 0x71, 0x54, 0x90, 0x79, 0x02, 0x75, 0xcd, 0x8c,
	0x0d, 0xa8, 0x5c, 0x90, 0x49, 0xcb, 0x68, 0x1b, 0x9d, 0x35, 0x27, 0x59, 0xe2, 0x0e, 0x54, 0xbf,
	0xb8, 0xc1, 0x98, 0xb4, 0xca, 0xc2, 0x26, 0x3f, 0x9e, 0x96, 0x9f, 0x18, 0xd6, 0x01, 0xdc, 0x17,
	0x69, 0xdc, 0xc8, 0x3f, 0xf3, 0xc9, 0x90, 0xbe, 0x8d, 0xa9, 0x47, 0x18, 0x7b, 0xce, 0x18, 0xf5,
	0x7c, 0x97, 0xfb, 0x34, 0x9c, 0xb1, 0xef, 0xc1, 0x96, 0xee, 0xf2, 0x62, 0xec, 0x0f, 0x18, 0xda,
	0xb0, 0x3d, 0x48, 0x8c, 0xfd, 0x48, 0x5a, 0xfb, 0xc3, 0xc4, 0x2c, 0x8e, 0xb1, 0xe6, 0x6c, 0x0d,
	0xae, 0xfb, 0x5b, 0xbf, 0xcb, 0xd0, 0xc9, 0x4f, 0xa8, 0x64, 0xf9, 0x65, 0xc0, 0x5d, 0xcf, 0x8d,
	0xfc, 0x7e, 0x3a, 0x85, 0xab, 0xf9, 0x2a, 0xc1, 0xde, 0x5c, 0x09, 0x56, 0x00, 0xd8, 0xce, 0x72,
	0x92, 0xd2, 0xde, 0xf6, 0x32, 0x5c, 0xcc, 0x21, 0xec, 0xe7, 0x42, 0x2c, 0x28, 0xc3, 0xa1, 0x5e,
	0x86, 0x7a, 0xb7, 0x29, 0x48, 0xcf, 0x69, 0xaa, 0x97, 0x67, 0x02, 0x55, 0x51, 0x59, 0x44, 0x58,
	0x49, 0x94, 0x55, 0x68, 0x62, 0x9d, 0xd8, 0x46, 0x94, 0x71, 0x55, 0x54, 0xb1, 0x4e, 0x6c, 0x91,
	0xcb, 0x47, 0xad, 0x8a, 0xb4, 0x25, 0x6b, 0x7c, 0x04, 0xeb, 0x03, 0xc2, 0xb8, 0x1f, 0x2a, 0xc9,
	0x56, 0x84, 0x64, 0x0d, 0x99, 0xfd, 0x6a, 0xc3, 0x49, 0x79, 0x59, 0x8f, 0x01, 0xdf, 0x47, 0x8c,
	0xc4, 0x5c, 0x10, 0x50, 0x4d, 0x80, 0x6d, 0xa8, 0x8a, 0xa6, 0x13, 0x44, 0xea, 0x5d, 0x10, 0x20,
	0xd2, 0x43, 0x6e, 0x24, 0xbd, 0x9f, 0x8a, 0x93, 0x92, 0x5b, 0x1d, 0xc0, 0x33, 0x12, 0x10, 0x4e,
	0x52, 0x70, 0x0b, 0x8e, 0x95, 0x00, 0xa4, 0x3c, 0x15, 0x00, 0x81, 0xba, 0x46, 0x16, 0x1f, 0xc0,
	0x96, 0x68, 0x0d, 0xbd, 0xef, 0x14, 0xcc, 0x66, 0xb2, 0xa1, 0x29, 0x8a, 0x4d, 0xa8, 0x7d, 0x25,
	0xfe, 0x70, 0x24, 0xa5, 0xda, 0x70, 0xd4, 0x97, 0x10, 0x8b, 0xc6, 0x5c, 0x88, 0xb5, 0xe1, 0x88,
	0xb5, 0x35, 0x81, 0xbd, 0x8c, 0xd2, 0x2e, 0x95, 0xf6, 0x86, 0xbb, 0x51, 0xbe, 0xe9, 0x6e, 0xfc,
	0x34, 0xa0, 0x23, 0xa5, 0xcb, 0x60, 0x30, 0x55, 0x8e, 0xc0, 0x9d, 0xec, 0xab, 0xa1, 0x2a, 0xd4,
	0x16, 0x15, 0xca, 0x02, 0xdc, 0xcb, 0x68, 0x75, 0xeb, 0x21, 0x1c, 0x14, 0xa0, 0xa4, 0x4a, 0xf4,
	0x01, 0x3a, 0xb2, 0x72, 0x05, 0xf8, 0x2f, 0x21, 0x64, 0x42, 0xa2, 0x00, 0xae, 0x22, 0xf1, 0xc7,
	0x80, 0xcd, 0xd3, 0x71, 0x70, 0xf1, 0x6e, 0x12, 0x7a, 0xd3, 0x64, 0xd6, 0x6c, 0xbe, 0x96, 0x45,
	0xef, 0xeb, 0x6d, 0xab, 0x76, 0x70, 0x98, 0x3f, 0x6b, 0x2a, 0x22, 0x38, 0x5f, 0xd1, 0xcc, 0xe1,
	0xf1, 0x6a, 0x65, 0xd5, 0x68, 0x94, 0x9d, 0xff, 0x44, 0xda, 0xfe, 0xa5, 0x1b, 0x45, 0x7e, 0x38,
	0x64, 0x16, 0x42, 0xe3, 0x8a, 0xb5, 0x3c, 0x4a, 0xf7, 0x6f, 0x15, 0x9a, 0xbd, 0xe4, 0xd1, 0xe9,
	0xcd, 0xde, 0x9c, 0x1e, 0x8d, 0xfc, 0x80, 0x72, 0x3c, 0x87, 0x75, 0xfd, 0x79, 0xc0, 0xd6, 0x82,
	0x17, 0x43, 0x9c, 0xdd, 0xbc, 0x75, 0xe3, 0x5b, 0x62, 0x95, 0xf0, 0x9b, 0x01, 0xed, 0xbc, 0xa9,
	0x89, 0x87, 0x05, 0x87, 0xab, 0xcc, 0x77, 0xb4, 0xd4, 0x28, 0xb6, 0x4a, 0x78, 0x0a, 0x75, 0x6d,
	0x60, 0xe0, 0xff, 0x22, 0x7e, 0x7e, 0xf4, 0x98, 0xad, 0xf9, 0x0d, 0x1d, 0x43, 0x9b, 0x19, 0x0a,
	0x63, 0x7e, 0xde, 0x28, 0x8c, 0x45, 0xe3, 0xa5, 0x84, 0xdf, 0x0d, 0xd8, 0xcf, 0xed, 0x75, 0x3c,
	0xd2, 0x58, 0xe4, 0xb7, 0xb9, 0x69, 0x17, 0x75, 0x4f, 0xd1, 0xc8, 0xed, 0x76, 0x45, 0xa3, 0xe8,
	0x6d, 0x53, 0x34, 0x8a, 0x5f, 0xa2, 0x12, 0x9e, 0xc0, 0xea, 0xb4, 0x1f, 0x71, 0x47, 0x44, 0x5f,
	0xbb, 0x54, 0xe6, 0xee, 0x35, 0xeb, 0x2c, 0xf4, 0x18, 0x6a, 0x2f, 0x89, 0x1b, 0xf0, 0x11, 0xa2,
	0x70, 0x91, 0x1f, 0xd3, 0xb0, 0xed, 0x94, 0x6d, 0x1a, 0xf4, 0xb1, 0x26, 0xfe, 0x9c, 0x8e, 0xff,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xad, 0x67, 0x0b, 0x0e, 0x66, 0x09, 0x00, 0x00,
}
