// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloud_controller.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	cloud_controller.proto
	istio.proto
	common.proto

It has these top-level messages:
	ListCfRoutesRequest
	ListCfRoutesResponse
	ListCfRouteMappingsRequest
	ListCfRouteMappingsResponse
	Route
	UpsertRouteRequest
	UpsertRouteResponse
	DeleteRouteRequest
	DeleteRouteResponse
	RouteMapping
	MapRouteRequest
	MapRouteResponse
	UnmapRouteRequest
	UnmapRouteResponse
	CapiDiegoProcessAssociation
	UpsertCapiDiegoProcessAssociationRequest
	UpsertCapiDiegoProcessAssociationResponse
	DeleteCapiDiegoProcessAssociationRequest
	DeleteCapiDiegoProcessAssociationResponse
	RoutesRequest
	RoutesResponse
	BackendSet
	Backend
	HealthResponse
	HealthRequest
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListCfRoutesRequest struct {
}

func (m *ListCfRoutesRequest) Reset()                    { *m = ListCfRoutesRequest{} }
func (m *ListCfRoutesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListCfRoutesRequest) ProtoMessage()               {}
func (*ListCfRoutesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ListCfRoutesResponse struct {
	// key is route guid
	// value is host
	Routes map[string]string `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ListCfRoutesResponse) Reset()                    { *m = ListCfRoutesResponse{} }
func (m *ListCfRoutesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListCfRoutesResponse) ProtoMessage()               {}
func (*ListCfRoutesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListCfRoutesResponse) GetRoutes() map[string]string {
	if m != nil {
		return m.Routes
	}
	return nil
}

type ListCfRouteMappingsRequest struct {
}

func (m *ListCfRouteMappingsRequest) Reset()                    { *m = ListCfRouteMappingsRequest{} }
func (m *ListCfRouteMappingsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListCfRouteMappingsRequest) ProtoMessage()               {}
func (*ListCfRouteMappingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListCfRouteMappingsResponse struct {
	// key is '<route guid>-<capi process guid>'
	// value is a route_mapping
	RouteMappings map[string]*RouteMapping `protobuf:"bytes,1,rep,name=route_mappings,json=routeMappings" json:"route_mappings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ListCfRouteMappingsResponse) Reset()                    { *m = ListCfRouteMappingsResponse{} }
func (m *ListCfRouteMappingsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListCfRouteMappingsResponse) ProtoMessage()               {}
func (*ListCfRouteMappingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListCfRouteMappingsResponse) GetRouteMappings() map[string]*RouteMapping {
	if m != nil {
		return m.RouteMappings
	}
	return nil
}

type Route struct {
	Guid string `protobuf:"bytes,1,opt,name=guid" json:"guid,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Route) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Route) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type UpsertRouteRequest struct {
	Route *Route `protobuf:"bytes,1,opt,name=route" json:"route,omitempty"`
}

func (m *UpsertRouteRequest) Reset()                    { *m = UpsertRouteRequest{} }
func (m *UpsertRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*UpsertRouteRequest) ProtoMessage()               {}
func (*UpsertRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpsertRouteRequest) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type UpsertRouteResponse struct {
}

func (m *UpsertRouteResponse) Reset()                    { *m = UpsertRouteResponse{} }
func (m *UpsertRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*UpsertRouteResponse) ProtoMessage()               {}
func (*UpsertRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteRouteRequest struct {
	Guid string `protobuf:"bytes,1,opt,name=guid" json:"guid,omitempty"`
}

func (m *DeleteRouteRequest) Reset()                    { *m = DeleteRouteRequest{} }
func (m *DeleteRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRouteRequest) ProtoMessage()               {}
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteRouteRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type DeleteRouteResponse struct {
}

func (m *DeleteRouteResponse) Reset()                    { *m = DeleteRouteResponse{} }
func (m *DeleteRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteRouteResponse) ProtoMessage()               {}
func (*DeleteRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type RouteMapping struct {
	CapiProcessGuid string `protobuf:"bytes,1,opt,name=capi_process_guid,json=capiProcessGuid" json:"capi_process_guid,omitempty"`
	RouteGuid       string `protobuf:"bytes,2,opt,name=route_guid,json=routeGuid" json:"route_guid,omitempty"`
}

func (m *RouteMapping) Reset()                    { *m = RouteMapping{} }
func (m *RouteMapping) String() string            { return proto.CompactTextString(m) }
func (*RouteMapping) ProtoMessage()               {}
func (*RouteMapping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RouteMapping) GetCapiProcessGuid() string {
	if m != nil {
		return m.CapiProcessGuid
	}
	return ""
}

func (m *RouteMapping) GetRouteGuid() string {
	if m != nil {
		return m.RouteGuid
	}
	return ""
}

type MapRouteRequest struct {
	RouteMapping *RouteMapping `protobuf:"bytes,1,opt,name=route_mapping,json=routeMapping" json:"route_mapping,omitempty"`
}

func (m *MapRouteRequest) Reset()                    { *m = MapRouteRequest{} }
func (m *MapRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*MapRouteRequest) ProtoMessage()               {}
func (*MapRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MapRouteRequest) GetRouteMapping() *RouteMapping {
	if m != nil {
		return m.RouteMapping
	}
	return nil
}

type MapRouteResponse struct {
}

func (m *MapRouteResponse) Reset()                    { *m = MapRouteResponse{} }
func (m *MapRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*MapRouteResponse) ProtoMessage()               {}
func (*MapRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type UnmapRouteRequest struct {
	RouteMapping *RouteMapping `protobuf:"bytes,1,opt,name=route_mapping,json=routeMapping" json:"route_mapping,omitempty"`
}

func (m *UnmapRouteRequest) Reset()                    { *m = UnmapRouteRequest{} }
func (m *UnmapRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*UnmapRouteRequest) ProtoMessage()               {}
func (*UnmapRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *UnmapRouteRequest) GetRouteMapping() *RouteMapping {
	if m != nil {
		return m.RouteMapping
	}
	return nil
}

type UnmapRouteResponse struct {
}

func (m *UnmapRouteResponse) Reset()                    { *m = UnmapRouteResponse{} }
func (m *UnmapRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*UnmapRouteResponse) ProtoMessage()               {}
func (*UnmapRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type CapiDiegoProcessAssociation struct {
	CapiProcessGuid   string   `protobuf:"bytes,1,opt,name=capi_process_guid,json=capiProcessGuid" json:"capi_process_guid,omitempty"`
	DiegoProcessGuids []string `protobuf:"bytes,2,rep,name=diego_process_guids,json=diegoProcessGuids" json:"diego_process_guids,omitempty"`
}

func (m *CapiDiegoProcessAssociation) Reset()                    { *m = CapiDiegoProcessAssociation{} }
func (m *CapiDiegoProcessAssociation) String() string            { return proto.CompactTextString(m) }
func (*CapiDiegoProcessAssociation) ProtoMessage()               {}
func (*CapiDiegoProcessAssociation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CapiDiegoProcessAssociation) GetCapiProcessGuid() string {
	if m != nil {
		return m.CapiProcessGuid
	}
	return ""
}

func (m *CapiDiegoProcessAssociation) GetDiegoProcessGuids() []string {
	if m != nil {
		return m.DiegoProcessGuids
	}
	return nil
}

type UpsertCapiDiegoProcessAssociationRequest struct {
	CapiDiegoProcessAssociation *CapiDiegoProcessAssociation `protobuf:"bytes,1,opt,name=capi_diego_process_association,json=capiDiegoProcessAssociation" json:"capi_diego_process_association,omitempty"`
}

func (m *UpsertCapiDiegoProcessAssociationRequest) Reset() {
	*m = UpsertCapiDiegoProcessAssociationRequest{}
}
func (m *UpsertCapiDiegoProcessAssociationRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertCapiDiegoProcessAssociationRequest) ProtoMessage()    {}
func (*UpsertCapiDiegoProcessAssociationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15}
}

func (m *UpsertCapiDiegoProcessAssociationRequest) GetCapiDiegoProcessAssociation() *CapiDiegoProcessAssociation {
	if m != nil {
		return m.CapiDiegoProcessAssociation
	}
	return nil
}

type UpsertCapiDiegoProcessAssociationResponse struct {
}

func (m *UpsertCapiDiegoProcessAssociationResponse) Reset() {
	*m = UpsertCapiDiegoProcessAssociationResponse{}
}
func (m *UpsertCapiDiegoProcessAssociationResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertCapiDiegoProcessAssociationResponse) ProtoMessage()    {}
func (*UpsertCapiDiegoProcessAssociationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{16}
}

type DeleteCapiDiegoProcessAssociationRequest struct {
	CapiDiegoProcessAssociation *CapiDiegoProcessAssociation `protobuf:"bytes,1,opt,name=capi_diego_process_association,json=capiDiegoProcessAssociation" json:"capi_diego_process_association,omitempty"`
}

func (m *DeleteCapiDiegoProcessAssociationRequest) Reset() {
	*m = DeleteCapiDiegoProcessAssociationRequest{}
}
func (m *DeleteCapiDiegoProcessAssociationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCapiDiegoProcessAssociationRequest) ProtoMessage()    {}
func (*DeleteCapiDiegoProcessAssociationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{17}
}

func (m *DeleteCapiDiegoProcessAssociationRequest) GetCapiDiegoProcessAssociation() *CapiDiegoProcessAssociation {
	if m != nil {
		return m.CapiDiegoProcessAssociation
	}
	return nil
}

type DeleteCapiDiegoProcessAssociationResponse struct {
}

func (m *DeleteCapiDiegoProcessAssociationResponse) Reset() {
	*m = DeleteCapiDiegoProcessAssociationResponse{}
}
func (m *DeleteCapiDiegoProcessAssociationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCapiDiegoProcessAssociationResponse) ProtoMessage()    {}
func (*DeleteCapiDiegoProcessAssociationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18}
}

func init() {
	proto.RegisterType((*ListCfRoutesRequest)(nil), "api.ListCfRoutesRequest")
	proto.RegisterType((*ListCfRoutesResponse)(nil), "api.ListCfRoutesResponse")
	proto.RegisterType((*ListCfRouteMappingsRequest)(nil), "api.ListCfRouteMappingsRequest")
	proto.RegisterType((*ListCfRouteMappingsResponse)(nil), "api.ListCfRouteMappingsResponse")
	proto.RegisterType((*Route)(nil), "api.Route")
	proto.RegisterType((*UpsertRouteRequest)(nil), "api.UpsertRouteRequest")
	proto.RegisterType((*UpsertRouteResponse)(nil), "api.UpsertRouteResponse")
	proto.RegisterType((*DeleteRouteRequest)(nil), "api.DeleteRouteRequest")
	proto.RegisterType((*DeleteRouteResponse)(nil), "api.DeleteRouteResponse")
	proto.RegisterType((*RouteMapping)(nil), "api.RouteMapping")
	proto.RegisterType((*MapRouteRequest)(nil), "api.MapRouteRequest")
	proto.RegisterType((*MapRouteResponse)(nil), "api.MapRouteResponse")
	proto.RegisterType((*UnmapRouteRequest)(nil), "api.UnmapRouteRequest")
	proto.RegisterType((*UnmapRouteResponse)(nil), "api.UnmapRouteResponse")
	proto.RegisterType((*CapiDiegoProcessAssociation)(nil), "api.CapiDiegoProcessAssociation")
	proto.RegisterType((*UpsertCapiDiegoProcessAssociationRequest)(nil), "api.UpsertCapiDiegoProcessAssociationRequest")
	proto.RegisterType((*UpsertCapiDiegoProcessAssociationResponse)(nil), "api.UpsertCapiDiegoProcessAssociationResponse")
	proto.RegisterType((*DeleteCapiDiegoProcessAssociationRequest)(nil), "api.DeleteCapiDiegoProcessAssociationRequest")
	proto.RegisterType((*DeleteCapiDiegoProcessAssociationResponse)(nil), "api.DeleteCapiDiegoProcessAssociationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CloudControllerCopilot service

type CloudControllerCopilotClient interface {
	ListCfRoutes(ctx context.Context, in *ListCfRoutesRequest, opts ...grpc.CallOption) (*ListCfRoutesResponse, error)
	ListCfRouteMappings(ctx context.Context, in *ListCfRouteMappingsRequest, opts ...grpc.CallOption) (*ListCfRouteMappingsResponse, error)
	UpsertRoute(ctx context.Context, in *UpsertRouteRequest, opts ...grpc.CallOption) (*UpsertRouteResponse, error)
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error)
	MapRoute(ctx context.Context, in *MapRouteRequest, opts ...grpc.CallOption) (*MapRouteResponse, error)
	UnmapRoute(ctx context.Context, in *UnmapRouteRequest, opts ...grpc.CallOption) (*UnmapRouteResponse, error)
	UpsertCapiDiegoProcessAssociation(ctx context.Context, in *UpsertCapiDiegoProcessAssociationRequest, opts ...grpc.CallOption) (*UpsertCapiDiegoProcessAssociationResponse, error)
	DeleteCapiDiegoProcessAssociation(ctx context.Context, in *DeleteCapiDiegoProcessAssociationRequest, opts ...grpc.CallOption) (*DeleteCapiDiegoProcessAssociationResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type cloudControllerCopilotClient struct {
	cc *grpc.ClientConn
}

func NewCloudControllerCopilotClient(cc *grpc.ClientConn) CloudControllerCopilotClient {
	return &cloudControllerCopilotClient{cc}
}

func (c *cloudControllerCopilotClient) ListCfRoutes(ctx context.Context, in *ListCfRoutesRequest, opts ...grpc.CallOption) (*ListCfRoutesResponse, error) {
	out := new(ListCfRoutesResponse)
	err := grpc.Invoke(ctx, "/api.CloudControllerCopilot/ListCfRoutes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) ListCfRouteMappings(ctx context.Context, in *ListCfRouteMappingsRequest, opts ...grpc.CallOption) (*ListCfRouteMappingsResponse, error) {
	out := new(ListCfRouteMappingsResponse)
	err := grpc.Invoke(ctx, "/api.CloudControllerCopilot/ListCfRouteMappings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) UpsertRoute(ctx context.Context, in *UpsertRouteRequest, opts ...grpc.CallOption) (*UpsertRouteResponse, error) {
	out := new(UpsertRouteResponse)
	err := grpc.Invoke(ctx, "/api.CloudControllerCopilot/UpsertRoute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error) {
	out := new(DeleteRouteResponse)
	err := grpc.Invoke(ctx, "/api.CloudControllerCopilot/DeleteRoute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) MapRoute(ctx context.Context, in *MapRouteRequest, opts ...grpc.CallOption) (*MapRouteResponse, error) {
	out := new(MapRouteResponse)
	err := grpc.Invoke(ctx, "/api.CloudControllerCopilot/MapRoute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) UnmapRoute(ctx context.Context, in *UnmapRouteRequest, opts ...grpc.CallOption) (*UnmapRouteResponse, error) {
	out := new(UnmapRouteResponse)
	err := grpc.Invoke(ctx, "/api.CloudControllerCopilot/UnmapRoute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) UpsertCapiDiegoProcessAssociation(ctx context.Context, in *UpsertCapiDiegoProcessAssociationRequest, opts ...grpc.CallOption) (*UpsertCapiDiegoProcessAssociationResponse, error) {
	out := new(UpsertCapiDiegoProcessAssociationResponse)
	err := grpc.Invoke(ctx, "/api.CloudControllerCopilot/UpsertCapiDiegoProcessAssociation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) DeleteCapiDiegoProcessAssociation(ctx context.Context, in *DeleteCapiDiegoProcessAssociationRequest, opts ...grpc.CallOption) (*DeleteCapiDiegoProcessAssociationResponse, error) {
	out := new(DeleteCapiDiegoProcessAssociationResponse)
	err := grpc.Invoke(ctx, "/api.CloudControllerCopilot/DeleteCapiDiegoProcessAssociation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudControllerCopilotClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := grpc.Invoke(ctx, "/api.CloudControllerCopilot/Health", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CloudControllerCopilot service

type CloudControllerCopilotServer interface {
	ListCfRoutes(context.Context, *ListCfRoutesRequest) (*ListCfRoutesResponse, error)
	ListCfRouteMappings(context.Context, *ListCfRouteMappingsRequest) (*ListCfRouteMappingsResponse, error)
	UpsertRoute(context.Context, *UpsertRouteRequest) (*UpsertRouteResponse, error)
	DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error)
	MapRoute(context.Context, *MapRouteRequest) (*MapRouteResponse, error)
	UnmapRoute(context.Context, *UnmapRouteRequest) (*UnmapRouteResponse, error)
	UpsertCapiDiegoProcessAssociation(context.Context, *UpsertCapiDiegoProcessAssociationRequest) (*UpsertCapiDiegoProcessAssociationResponse, error)
	DeleteCapiDiegoProcessAssociation(context.Context, *DeleteCapiDiegoProcessAssociationRequest) (*DeleteCapiDiegoProcessAssociationResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

func RegisterCloudControllerCopilotServer(s *grpc.Server, srv CloudControllerCopilotServer) {
	s.RegisterService(&_CloudControllerCopilot_serviceDesc, srv)
}

func _CloudControllerCopilot_ListCfRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCfRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).ListCfRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/ListCfRoutes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).ListCfRoutes(ctx, req.(*ListCfRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_ListCfRouteMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCfRouteMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).ListCfRouteMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/ListCfRouteMappings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).ListCfRouteMappings(ctx, req.(*ListCfRouteMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_UpsertRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).UpsertRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/UpsertRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).UpsertRoute(ctx, req.(*UpsertRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/DeleteRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_MapRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).MapRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/MapRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).MapRoute(ctx, req.(*MapRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_UnmapRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmapRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).UnmapRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/UnmapRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).UnmapRoute(ctx, req.(*UnmapRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_UpsertCapiDiegoProcessAssociation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCapiDiegoProcessAssociationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).UpsertCapiDiegoProcessAssociation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/UpsertCapiDiegoProcessAssociation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).UpsertCapiDiegoProcessAssociation(ctx, req.(*UpsertCapiDiegoProcessAssociationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_DeleteCapiDiegoProcessAssociation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCapiDiegoProcessAssociationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).DeleteCapiDiegoProcessAssociation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/DeleteCapiDiegoProcessAssociation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).DeleteCapiDiegoProcessAssociation(ctx, req.(*DeleteCapiDiegoProcessAssociationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudControllerCopilot_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudControllerCopilotServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CloudControllerCopilot/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudControllerCopilotServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudControllerCopilot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CloudControllerCopilot",
	HandlerType: (*CloudControllerCopilotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCfRoutes",
			Handler:    _CloudControllerCopilot_ListCfRoutes_Handler,
		},
		{
			MethodName: "ListCfRouteMappings",
			Handler:    _CloudControllerCopilot_ListCfRouteMappings_Handler,
		},
		{
			MethodName: "UpsertRoute",
			Handler:    _CloudControllerCopilot_UpsertRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _CloudControllerCopilot_DeleteRoute_Handler,
		},
		{
			MethodName: "MapRoute",
			Handler:    _CloudControllerCopilot_MapRoute_Handler,
		},
		{
			MethodName: "UnmapRoute",
			Handler:    _CloudControllerCopilot_UnmapRoute_Handler,
		},
		{
			MethodName: "UpsertCapiDiegoProcessAssociation",
			Handler:    _CloudControllerCopilot_UpsertCapiDiegoProcessAssociation_Handler,
		},
		{
			MethodName: "DeleteCapiDiegoProcessAssociation",
			Handler:    _CloudControllerCopilot_DeleteCapiDiegoProcessAssociation_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CloudControllerCopilot_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud_controller.proto",
}

func init() { proto.RegisterFile("cloud_controller.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 676 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0xcd, 0x36, 0x36, 0xd8, 0x9b, 0xd4, 0x36, 0xb7, 0x69, 0x1b, 0xb7, 0x7e, 0xc4, 0x05, 0x31,
	0x2a, 0xae, 0x90, 0x42, 0xb1, 0x82, 0x88, 0xa6, 0x45, 0x45, 0x0b, 0xb2, 0xd2, 0x07, 0xfb, 0x12,
	0xd6, 0xcd, 0xd8, 0x2e, 0x6e, 0x76, 0xc6, 0x9d, 0x89, 0xd0, 0x57, 0xf1, 0x07, 0xe8, 0x1f, 0xf3,
	0x37, 0xc9, 0xce, 0x4c, 0x92, 0x99, 0x64, 0xdb, 0x44, 0xf0, 0xc1, 0xb7, 0xec, 0xfd, 0x38, 0xf7,
	0x9c, 0x3b, 0x33, 0x87, 0xc0, 0x56, 0x94, 0xd0, 0x61, 0xbf, 0x17, 0xd1, 0x54, 0x64, 0x34, 0x49,
	0x48, 0xe6, 0xb3, 0x8c, 0x0a, 0x8a, 0xe5, 0x90, 0xc5, 0x6e, 0x2d, 0xa2, 0x83, 0x01, 0x4d, 0x55,
	0xc8, 0xdb, 0x84, 0x8d, 0x77, 0x31, 0x17, 0xdd, 0xcf, 0x01, 0x1d, 0x0a, 0xc2, 0x03, 0xf2, 0x75,
	0x48, 0xb8, 0xf0, 0x7e, 0x3a, 0xd0, 0xb0, 0xe3, 0x9c, 0xd1, 0x94, 0x13, 0x7c, 0x06, 0x95, 0x4c,
	0x46, 0x9a, 0x4e, 0xab, 0xdc, 0xae, 0x76, 0xee, 0xfa, 0x21, 0x8b, 0xfd, 0xa2, 0x52, 0x5f, 0x7d,
	0x1e, 0xa6, 0x22, 0x3b, 0x0f, 0x74, 0x93, 0xbb, 0x0f, 0x55, 0x23, 0x8c, 0xeb, 0x50, 0xfe, 0x42,
	0xce, 0x9b, 0x4e, 0xcb, 0x69, 0xaf, 0x04, 0xf9, 0x4f, 0x6c, 0xc0, 0xf2, 0xb7, 0x30, 0x19, 0x92,
	0xe6, 0x92, 0x8c, 0xa9, 0x8f, 0xa7, 0x4b, 0x4f, 0x1c, 0xef, 0x06, 0xb8, 0xc6, 0x98, 0xa3, 0x90,
	0xb1, 0x38, 0x3d, 0x1d, 0x13, 0xfe, 0xed, 0xc0, 0x4e, 0x61, 0x5a, 0xf3, 0x3e, 0x81, 0x6b, 0x92,
	0x42, 0x6f, 0xa0, 0x33, 0x9a, 0xff, 0xee, 0x34, 0xff, 0xe9, 0x4e, 0xdf, 0x8a, 0x2a, 0x35, 0xab,
	0x99, 0x19, 0x73, 0x3f, 0x00, 0xce, 0x16, 0x15, 0x68, 0xbb, 0x67, 0x6a, 0xab, 0x76, 0xea, 0x72,
	0xb4, 0xd9, 0x69, 0xca, 0x7d, 0x0c, 0xcb, 0x32, 0x85, 0x08, 0x57, 0x4e, 0x87, 0x71, 0x5f, 0x03,
	0xc9, 0xdf, 0x79, 0xec, 0x8c, 0x72, 0xa1, 0x97, 0x24, 0x7f, 0x7b, 0x7b, 0x80, 0xc7, 0x8c, 0x93,
	0x4c, 0xc8, 0x36, 0xbd, 0x17, 0x6c, 0xc1, 0xb2, 0x24, 0x2b, 0xdb, 0xab, 0x1d, 0x98, 0xcc, 0x0c,
	0x54, 0x22, 0xbf, 0x01, 0x56, 0x9f, 0x92, 0xed, 0xb5, 0x01, 0x0f, 0x48, 0x42, 0x04, 0xb1, 0xe0,
	0x0a, 0xc8, 0xe4, 0x00, 0x56, 0xa5, 0x06, 0xf8, 0x08, 0x35, 0x53, 0x1b, 0x3e, 0x80, 0x7a, 0x14,
	0xb2, 0xb8, 0xc7, 0x32, 0x1a, 0x11, 0xce, 0x7b, 0x06, 0xce, 0x5a, 0x9e, 0x78, 0xaf, 0xe2, 0xaf,
	0x72, 0x7d, 0x37, 0x01, 0xd4, 0x69, 0xc9, 0x22, 0xa5, 0x72, 0x45, 0x46, 0xf2, 0xb4, 0xf7, 0x06,
	0xd6, 0x8e, 0x42, 0x66, 0x11, 0xdb, 0x83, 0x55, 0xeb, 0x7c, 0xb5, 0xde, 0x82, 0x1d, 0xd7, 0xcc,
	0xc3, 0xf3, 0x10, 0xd6, 0x27, 0x50, 0x9a, 0xf9, 0x5b, 0xa8, 0x1f, 0xa7, 0x83, 0x7f, 0x34, 0xa0,
	0x01, 0x68, 0x82, 0xe9, 0x11, 0xe7, 0xb0, 0xd3, 0x0d, 0x59, 0x7c, 0x10, 0x93, 0x53, 0xaa, 0x85,
	0xbf, 0xe0, 0x9c, 0x46, 0x71, 0x28, 0x62, 0x9a, 0xfe, 0xd5, 0xae, 0x7c, 0xd8, 0xe8, 0xe7, 0x30,
	0x56, 0x31, 0x6f, 0x2e, 0xb5, 0xca, 0xed, 0x95, 0xa0, 0xde, 0x37, 0x26, 0xe4, 0xe5, 0xdc, 0xfb,
	0xe5, 0x40, 0x5b, 0x1d, 0xf8, 0x25, 0x0c, 0x46, 0xaa, 0x09, 0xdc, 0x92, 0x44, 0xec, 0x09, 0xe1,
	0xa4, 0x50, 0xaf, 0xa1, 0x25, 0xd7, 0x70, 0x19, 0xe0, 0x4e, 0x74, 0x71, 0xd2, 0x7b, 0x08, 0xf7,
	0x17, 0xa0, 0xa4, 0x77, 0x97, 0x0b, 0x50, 0x17, 0xee, 0xbf, 0x12, 0xb0, 0x00, 0x25, 0x25, 0xa0,
	0xf3, 0xbd, 0x02, 0x5b, 0xdd, 0xdc, 0xa1, 0xbb, 0x63, 0x83, 0xee, 0x52, 0x16, 0x27, 0x54, 0xe0,
	0x21, 0xd4, 0x4c, 0x2f, 0xc5, 0x66, 0x81, 0xbd, 0x4a, 0x61, 0xee, 0xf5, 0x0b, 0x8d, 0xd7, 0x2b,
	0xe1, 0x89, 0xe5, 0xea, 0x23, 0x5f, 0xc2, 0xdb, 0x17, 0x9b, 0x9d, 0x02, 0x6d, 0xcd, 0x73, 0x43,
	0xaf, 0x84, 0x2f, 0xa1, 0x6a, 0xf8, 0x05, 0x6e, 0xcb, 0x96, 0x59, 0xe7, 0x71, 0x9b, 0xb3, 0x09,
	0x13, 0xc3, 0xb0, 0x0c, 0x8d, 0x31, 0x6b, 0x37, 0x1a, 0xa3, 0xc8, 0x5d, 0x4a, 0xb8, 0x0f, 0x57,
	0x47, 0x2f, 0x17, 0x1b, 0xb2, 0x6e, 0xca, 0x13, 0xdc, 0xcd, 0xa9, 0xe8, 0xb8, 0xf5, 0x39, 0xc0,
	0xe4, 0x4d, 0xe2, 0x96, 0x22, 0x3a, 0xfd, 0xe2, 0xdd, 0xed, 0x99, 0xf8, 0x18, 0xe0, 0x87, 0x03,
	0x77, 0xe6, 0x5e, 0x58, 0x7c, 0x64, 0x6c, 0x60, 0xfe, 0x55, 0x75, 0xfd, 0x45, 0xcb, 0x2d, 0x1a,
	0x73, 0xaf, 0x9d, 0xa6, 0xb1, 0xe8, 0x8b, 0xd1, 0x34, 0x16, 0xbe, 0xcd, 0x5e, 0x09, 0x77, 0xa1,
	0xf2, 0x9a, 0x84, 0x89, 0x38, 0x43, 0x94, 0xbd, 0xea, 0x63, 0x84, 0xb7, 0x61, 0xc5, 0x46, 0x4d,
	0x9f, 0x2a, 0xf2, 0xff, 0xc7, 0xee, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xec, 0xa3, 0x3c,
	0xac, 0x08, 0x00, 0x00,
}
