// Code generated by protoc-gen-go. DO NOT EDIT.
// source: istio.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type InternalRoutesRequest struct {
}

func (m *InternalRoutesRequest) Reset()                    { *m = InternalRoutesRequest{} }
func (m *InternalRoutesRequest) String() string            { return proto.CompactTextString(m) }
func (*InternalRoutesRequest) ProtoMessage()               {}
func (*InternalRoutesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type InternalRoutesResponse struct {
	InternalRoutes []*InternalRouteWithBackends `protobuf:"bytes,1,rep,name=internal_routes,json=internalRoutes" json:"internal_routes,omitempty"`
}

func (m *InternalRoutesResponse) Reset()                    { *m = InternalRoutesResponse{} }
func (m *InternalRoutesResponse) String() string            { return proto.CompactTextString(m) }
func (*InternalRoutesResponse) ProtoMessage()               {}
func (*InternalRoutesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *InternalRoutesResponse) GetInternalRoutes() []*InternalRouteWithBackends {
	if m != nil {
		return m.InternalRoutes
	}
	return nil
}

type InternalRouteWithBackends struct {
	Hostname string      `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Vip      string      `protobuf:"bytes,2,opt,name=vip" json:"vip,omitempty"`
	Backends *BackendSet `protobuf:"bytes,3,opt,name=backends" json:"backends,omitempty"`
}

func (m *InternalRouteWithBackends) Reset()                    { *m = InternalRouteWithBackends{} }
func (m *InternalRouteWithBackends) String() string            { return proto.CompactTextString(m) }
func (*InternalRouteWithBackends) ProtoMessage()               {}
func (*InternalRouteWithBackends) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *InternalRouteWithBackends) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *InternalRouteWithBackends) GetVip() string {
	if m != nil {
		return m.Vip
	}
	return ""
}

func (m *InternalRouteWithBackends) GetBackends() *BackendSet {
	if m != nil {
		return m.Backends
	}
	return nil
}

type RoutesRequest struct {
}

func (m *RoutesRequest) Reset()                    { *m = RoutesRequest{} }
func (m *RoutesRequest) String() string            { return proto.CompactTextString(m) }
func (*RoutesRequest) ProtoMessage()               {}
func (*RoutesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type RoutesResponse struct {
	Routes []*RouteWithBackends `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *RoutesResponse) Reset()                    { *m = RoutesResponse{} }
func (m *RoutesResponse) String() string            { return proto.CompactTextString(m) }
func (*RoutesResponse) ProtoMessage()               {}
func (*RoutesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *RoutesResponse) GetRoutes() []*RouteWithBackends {
	if m != nil {
		return m.Routes
	}
	return nil
}

type RouteWithBackends struct {
	Hostname string      `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Backends *BackendSet `protobuf:"bytes,3,opt,name=backends" json:"backends,omitempty"`
}

func (m *RouteWithBackends) Reset()                    { *m = RouteWithBackends{} }
func (m *RouteWithBackends) String() string            { return proto.CompactTextString(m) }
func (*RouteWithBackends) ProtoMessage()               {}
func (*RouteWithBackends) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *RouteWithBackends) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RouteWithBackends) GetBackends() *BackendSet {
	if m != nil {
		return m.Backends
	}
	return nil
}

type BackendSet struct {
	Backends []*Backend `protobuf:"bytes,1,rep,name=backends" json:"backends,omitempty"`
}

func (m *BackendSet) Reset()                    { *m = BackendSet{} }
func (m *BackendSet) String() string            { return proto.CompactTextString(m) }
func (*BackendSet) ProtoMessage()               {}
func (*BackendSet) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *BackendSet) GetBackends() []*Backend {
	if m != nil {
		return m.Backends
	}
	return nil
}

type Backend struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Port    uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *Backend) Reset()                    { *m = Backend{} }
func (m *Backend) String() string            { return proto.CompactTextString(m) }
func (*Backend) ProtoMessage()               {}
func (*Backend) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *Backend) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Backend) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*InternalRoutesRequest)(nil), "api.InternalRoutesRequest")
	proto.RegisterType((*InternalRoutesResponse)(nil), "api.InternalRoutesResponse")
	proto.RegisterType((*InternalRouteWithBackends)(nil), "api.InternalRouteWithBackends")
	proto.RegisterType((*RoutesRequest)(nil), "api.RoutesRequest")
	proto.RegisterType((*RoutesResponse)(nil), "api.RoutesResponse")
	proto.RegisterType((*RouteWithBackends)(nil), "api.RouteWithBackends")
	proto.RegisterType((*BackendSet)(nil), "api.BackendSet")
	proto.RegisterType((*Backend)(nil), "api.Backend")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IstioCopilot service

type IstioCopilotClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Routes(ctx context.Context, in *RoutesRequest, opts ...grpc.CallOption) (*RoutesResponse, error)
	InternalRoutes(ctx context.Context, in *InternalRoutesRequest, opts ...grpc.CallOption) (*InternalRoutesResponse, error)
}

type istioCopilotClient struct {
	cc *grpc.ClientConn
}

func NewIstioCopilotClient(cc *grpc.ClientConn) IstioCopilotClient {
	return &istioCopilotClient{cc}
}

func (c *istioCopilotClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := grpc.Invoke(ctx, "/api.IstioCopilot/Health", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *istioCopilotClient) Routes(ctx context.Context, in *RoutesRequest, opts ...grpc.CallOption) (*RoutesResponse, error) {
	out := new(RoutesResponse)
	err := grpc.Invoke(ctx, "/api.IstioCopilot/Routes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *istioCopilotClient) InternalRoutes(ctx context.Context, in *InternalRoutesRequest, opts ...grpc.CallOption) (*InternalRoutesResponse, error) {
	out := new(InternalRoutesResponse)
	err := grpc.Invoke(ctx, "/api.IstioCopilot/InternalRoutes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IstioCopilot service

type IstioCopilotServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Routes(context.Context, *RoutesRequest) (*RoutesResponse, error)
	InternalRoutes(context.Context, *InternalRoutesRequest) (*InternalRoutesResponse, error)
}

func RegisterIstioCopilotServer(s *grpc.Server, srv IstioCopilotServer) {
	s.RegisterService(&_IstioCopilot_serviceDesc, srv)
}

func _IstioCopilot_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IstioCopilotServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IstioCopilot/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IstioCopilotServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IstioCopilot_Routes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IstioCopilotServer).Routes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IstioCopilot/Routes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IstioCopilotServer).Routes(ctx, req.(*RoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IstioCopilot_InternalRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IstioCopilotServer).InternalRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IstioCopilot/InternalRoutes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IstioCopilotServer).InternalRoutes(ctx, req.(*InternalRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IstioCopilot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.IstioCopilot",
	HandlerType: (*IstioCopilotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _IstioCopilot_Health_Handler,
		},
		{
			MethodName: "Routes",
			Handler:    _IstioCopilot_Routes_Handler,
		},
		{
			MethodName: "InternalRoutes",
			Handler:    _IstioCopilot_InternalRoutes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "istio.proto",
}

func init() { proto.RegisterFile("istio.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x4f, 0x3a, 0x31,
	0x10, 0x65, 0x7f, 0xfb, 0x0b, 0xe0, 0xf0, 0x4f, 0xc7, 0x88, 0xeb, 0x9a, 0x18, 0xd2, 0xd3, 0x26,
	0x26, 0x7b, 0x80, 0x44, 0xaf, 0x46, 0x0f, 0x4a, 0xbc, 0xd5, 0x83, 0x17, 0x13, 0x53, 0xa0, 0x09,
	0x8d, 0xd0, 0xd6, 0x6d, 0xe1, 0x1b, 0xfa, 0xbd, 0x0c, 0xdd, 0x82, 0x14, 0xf4, 0xc0, 0xad, 0xf3,
	0x66, 0xde, 0xeb, 0xbc, 0x97, 0x81, 0x86, 0x30, 0x56, 0xa8, 0x5c, 0x17, 0xca, 0x2a, 0x8c, 0x99,
	0x16, 0x69, 0x73, 0xac, 0xe6, 0x73, 0x25, 0x4b, 0x88, 0x9c, 0xc3, 0xd9, 0x50, 0x5a, 0x5e, 0x48,
	0x36, 0xa3, 0x6a, 0x61, 0xb9, 0xa1, 0xfc, 0x73, 0xc1, 0x8d, 0x25, 0x0c, 0xba, 0xbb, 0x0d, 0xa3,
	0x95, 0x34, 0x1c, 0x1f, 0xa1, 0x23, 0x7c, 0xe7, 0xbd, 0x70, 0xad, 0x24, 0xea, 0xc5, 0x59, 0xa3,
	0x7f, 0x95, 0x33, 0x2d, 0xf2, 0x80, 0xf5, 0x2a, 0xec, 0xf4, 0x9e, 0x8d, 0x3f, 0xb8, 0x9c, 0x18,
	0xda, 0x16, 0x81, 0x20, 0x59, 0xc2, 0xc5, 0x9f, 0xc3, 0x98, 0x42, 0x7d, 0xaa, 0x8c, 0x95, 0x6c,
	0xce, 0x93, 0xa8, 0x17, 0x65, 0x47, 0x74, 0x53, 0xe3, 0x31, 0xc4, 0x4b, 0xa1, 0x93, 0x7f, 0x0e,
	0x5e, 0x3d, 0xf1, 0x1a, 0xea, 0x23, 0xcf, 0x4c, 0xe2, 0x5e, 0x94, 0x35, 0xfa, 0x1d, 0xb7, 0x8c,
	0x97, 0x7b, 0xe1, 0x96, 0x6e, 0x06, 0x48, 0x07, 0x5a, 0xa1, 0xd7, 0x3b, 0x68, 0xef, 0x78, 0xcc,
	0xa1, 0x1a, 0x58, 0xeb, 0x3a, 0xb5, 0x7d, 0x4b, 0x7e, 0x8a, 0xbc, 0xc1, 0xc9, 0x61, 0x16, 0x0e,
	0x5a, 0xf8, 0x06, 0xe0, 0x07, 0xc7, 0x6c, 0x8b, 0x5a, 0x6e, 0xd7, 0xdc, 0xa6, 0x6e, 0xf1, 0x6e,
	0xa1, 0xe6, 0x41, 0x4c, 0xa0, 0xc6, 0x26, 0x93, 0x82, 0x1b, 0xe3, 0x57, 0x59, 0x97, 0x88, 0xf0,
	0x5f, 0xab, 0xc2, 0xba, 0x34, 0x5b, 0xd4, 0xbd, 0xfb, 0x5f, 0x11, 0x34, 0x87, 0xab, 0xc3, 0x79,
	0x50, 0x5a, 0xcc, 0x94, 0xc5, 0x01, 0x54, 0x9f, 0x38, 0x9b, 0xd9, 0x29, 0xa2, 0xfb, 0xab, 0x2c,
	0x7c, 0x7e, 0xe9, 0x69, 0x80, 0x95, 0x11, 0x92, 0xca, 0x8a, 0x54, 0xc6, 0xea, 0x49, 0x41, 0xe8,
	0x9e, 0x14, 0xe6, 0x4e, 0x2a, 0xf8, 0x0c, 0xed, 0xf0, 0xee, 0x30, 0xdd, 0x3f, 0xab, 0x8d, 0xc8,
	0xe5, 0xaf, 0xbd, 0xb5, 0xd8, 0xa8, 0xea, 0x8e, 0x7c, 0xf0, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xa1,
	0xe6, 0x01, 0x27, 0x06, 0x03, 0x00, 0x00,
}
