// Code generated by protoc-gen-go. DO NOT EDIT.
// source: istio.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RouteWithBackends struct {
	Hostname             string      `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Path                 string      `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Backends             *BackendSet `protobuf:"bytes,3,opt,name=backends,proto3" json:"backends,omitempty"`
	CapiProcessGuid      string      `protobuf:"bytes,4,opt,name=capi_process_guid,json=capiProcessGuid,proto3" json:"capi_process_guid,omitempty"`
	RouteWeight          int32       `protobuf:"varint,5,opt,name=route_weight,json=routeWeight,proto3" json:"route_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RouteWithBackends) Reset()         { *m = RouteWithBackends{} }
func (m *RouteWithBackends) String() string { return proto.CompactTextString(m) }
func (*RouteWithBackends) ProtoMessage()    {}
func (*RouteWithBackends) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af1f0fbc99b8df1, []int{0}
}

func (m *RouteWithBackends) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteWithBackends.Unmarshal(m, b)
}
func (m *RouteWithBackends) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteWithBackends.Marshal(b, m, deterministic)
}
func (m *RouteWithBackends) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteWithBackends.Merge(m, src)
}
func (m *RouteWithBackends) XXX_Size() int {
	return xxx_messageInfo_RouteWithBackends.Size(m)
}
func (m *RouteWithBackends) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteWithBackends.DiscardUnknown(m)
}

var xxx_messageInfo_RouteWithBackends proto.InternalMessageInfo

func (m *RouteWithBackends) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RouteWithBackends) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RouteWithBackends) GetBackends() *BackendSet {
	if m != nil {
		return m.Backends
	}
	return nil
}

func (m *RouteWithBackends) GetCapiProcessGuid() string {
	if m != nil {
		return m.CapiProcessGuid
	}
	return ""
}

func (m *RouteWithBackends) GetRouteWeight() int32 {
	if m != nil {
		return m.RouteWeight
	}
	return 0
}

type BackendSet struct {
	Backends             []*Backend `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BackendSet) Reset()         { *m = BackendSet{} }
func (m *BackendSet) String() string { return proto.CompactTextString(m) }
func (*BackendSet) ProtoMessage()    {}
func (*BackendSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af1f0fbc99b8df1, []int{1}
}

func (m *BackendSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendSet.Unmarshal(m, b)
}
func (m *BackendSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendSet.Marshal(b, m, deterministic)
}
func (m *BackendSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendSet.Merge(m, src)
}
func (m *BackendSet) XXX_Size() int {
	return xxx_messageInfo_BackendSet.Size(m)
}
func (m *BackendSet) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendSet.DiscardUnknown(m)
}

var xxx_messageInfo_BackendSet proto.InternalMessageInfo

func (m *BackendSet) GetBackends() []*Backend {
	if m != nil {
		return m.Backends
	}
	return nil
}

type Backend struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Backend) Reset()         { *m = Backend{} }
func (m *Backend) String() string { return proto.CompactTextString(m) }
func (*Backend) ProtoMessage()    {}
func (*Backend) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af1f0fbc99b8df1, []int{2}
}

func (m *Backend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Backend.Unmarshal(m, b)
}
func (m *Backend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Backend.Marshal(b, m, deterministic)
}
func (m *Backend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Backend.Merge(m, src)
}
func (m *Backend) XXX_Size() int {
	return xxx_messageInfo_Backend.Size(m)
}
func (m *Backend) XXX_DiscardUnknown() {
	xxx_messageInfo_Backend.DiscardUnknown(m)
}

var xxx_messageInfo_Backend proto.InternalMessageInfo

func (m *Backend) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Backend) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*RouteWithBackends)(nil), "api.RouteWithBackends")
	proto.RegisterType((*BackendSet)(nil), "api.BackendSet")
	proto.RegisterType((*Backend)(nil), "api.Backend")
}

func init() { proto.RegisterFile("istio.proto", fileDescriptor_8af1f0fbc99b8df1) }

var fileDescriptor_8af1f0fbc99b8df1 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x65, 0xd2, 0xd2, 0x72, 0x29, 0xaa, 0xea, 0xc9, 0x62, 0x0a, 0x99, 0x2c, 0x90, 0x32,
	0x14, 0x09, 0x76, 0x16, 0x56, 0x64, 0x86, 0x8e, 0x91, 0x1b, 0x5b, 0xcd, 0x09, 0x51, 0x5b, 0xf6,
	0x45, 0x3c, 0x1e, 0xaf, 0x86, 0x7a, 0x84, 0x36, 0xdb, 0xdd, 0x67, 0xfb, 0xfc, 0xfd, 0x07, 0x25,
	0x66, 0xc2, 0xd0, 0xc4, 0x14, 0x28, 0xc8, 0xc2, 0x46, 0xac, 0x7f, 0x04, 0x6c, 0x4c, 0x18, 0xc8,
	0xef, 0x90, 0xfa, 0x57, 0xdb, 0x7d, 0xfa, 0xa3, 0xcb, 0xf2, 0x0e, 0x96, 0x7d, 0xc8, 0x74, 0xb4,
	0x5f, 0x5e, 0x89, 0x4a, 0xe8, 0x1b, 0x73, 0xee, 0xa5, 0x84, 0x59, 0xb4, 0xd4, 0xab, 0x2b, 0xe6,
	0x5c, 0xcb, 0x47, 0x58, 0xee, 0xc7, 0xb7, 0xaa, 0xa8, 0x84, 0x2e, 0xb7, 0xeb, 0xc6, 0x46, 0x6c,
	0xc6, 0x81, 0x1f, 0x9e, 0xcc, 0xf9, 0x82, 0x7c, 0x80, 0x4d, 0x67, 0x23, 0xb6, 0x31, 0x85, 0xce,
	0xe7, 0xdc, 0x1e, 0x06, 0x74, 0x6a, 0xc6, 0xd3, 0xd6, 0xa7, 0x83, 0xf7, 0x3f, 0xfe, 0x36, 0xa0,
	0x93, 0xf7, 0xb0, 0x4a, 0x27, 0xbb, 0xf6, 0xdb, 0xe3, 0xa1, 0x27, 0x35, 0xaf, 0x84, 0x9e, 0x9b,
	0x92, 0xd9, 0x8e, 0x51, 0xfd, 0x0c, 0x70, 0xf9, 0x46, 0xea, 0x89, 0x89, 0xa8, 0x0a, 0x5d, 0x6e,
	0x57, 0x53, 0x93, 0x8b, 0x46, 0xfd, 0x02, 0x8b, 0x11, 0x4a, 0x05, 0x0b, 0xeb, 0x5c, 0xf2, 0x39,
	0x8f, 0x69, 0xff, 0x5b, 0x0e, 0x1b, 0x12, 0x71, 0xd8, 0x5b, 0xc3, 0xf5, 0xfe, 0x9a, 0xd7, 0xf7,
	0xf4, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x26, 0xd3, 0x52, 0x88, 0x4d, 0x01, 0x00, 0x00,
}
